In [211]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [212]:
dp1 = {'method': 'drop','percent': '1%','start_lat': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'start_lon': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'end_lat': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'end_lon': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'usertype': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'hour': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'temp': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'feelslike': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'dew': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'snowdepth': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'winddir': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'sealevelpressure': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'visibility': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'solarradiation': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'conditions': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'dist': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'birthyear': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'holiday': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'day': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'month': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269},
 'gender': {'MAE': 1.573023484558106,
  'MSE': 5.00423392065178,
  'RMSE': 2.23701451060376,
  'R2': 0.5266292556125269}}

In [213]:
dp2 = {'method': 'mode','percent': '1%','start_lat': {'MAE': 1.5723051733197362,
  'MSE': 4.999626510089749,
  'RMSE': 2.23598446105731,
  'R2': 0.5272344551340956},
 'start_lon': {'MAE': 1.5723482616373556,
  'MSE': 4.9998605199374,
  'RMSE': 2.236036788592129,
  'R2': 0.5272123271225521},
 'end_lat': {'MAE': 1.5723165458096728,
  'MSE': 4.9995519590925355,
  'RMSE': 2.235967790262761,
  'R2': 0.5272415046892467},
 'end_lon': {'MAE': 1.5723300036668895,
  'MSE': 4.999584618650703,
  'RMSE': 2.2359750934772737,
  'R2': 0.527238416395795},
 'usertype': {'MAE': 1.572419862390175,
  'MSE': 4.999829468190998,
  'RMSE': 2.236029845102922,
  'R2': 0.527215263381046},
 'hour': {'MAE': 1.5724188623066166,
  'MSE': 5.000332253826668,
  'RMSE': 2.2361422704798253,
  'R2': 0.5271677198846431},
 'temp': {'MAE': 1.5724215285461476,
  'MSE': 5.000114797855349,
  'RMSE': 2.236093646933274,
  'R2': 0.5271882825587864},
 'feelslike': {'MAE': 1.572435206329298,
  'MSE': 5.000185990010771,
  'RMSE': 2.2361095657437655,
  'R2': 0.5271815506162942},
 'dew': {'MAE': 1.5722919590477331,
  'MSE': 4.999548651330092,
  'RMSE': 2.2359670505913303,
  'R2': 0.5272418174718337},
 'snowdepth': {'MAE': 1.5723463739306578,
  'MSE': 4.999723037374943,
  'RMSE': 2.2360060459164557,
  'R2': 0.5272253274973637},
 'winddir': {'MAE': 1.5723250752839668,
  'MSE': 4.999626451268593,
  'RMSE': 2.2359844479040083,
  'R2': 0.5272344606962343},
 'sealevelpressure': {'MAE': 1.572316078113497,
  'MSE': 4.999572913903371,
  'RMSE': 2.2359724761059496,
  'R2': 0.5272395231987209},
 'visibility': {'MAE': 1.5723137828263463,
  'MSE': 4.999587184426877,
  'RMSE': 2.235975667226027,
  'R2': 0.5272381737755576},
 'solarradiation': {'MAE': 1.5722502661137219,
  'MSE': 4.999208161460294,
  'RMSE': 2.2358909100088704,
  'R2': 0.5272740142526315},
 'conditions': {'MAE': 1.5723263073114115,
  'MSE': 4.999615788934334,
  'RMSE': 2.2359820636432515,
  'R2': 0.5272354689284002},
 'dist': {'MAE': 1.5829735639670375,
  'MSE': 5.065700316040069,
  'RMSE': 2.2507110689824383,
  'R2': 0.5209865046505091},
 'birthyear': {'MAE': 1.5723843460439766,
  'MSE': 4.9997601942964565,
  'RMSE': 2.2360143546713775,
  'R2': 0.5272218139324585},
 'holiday': {'MAE': 1.5723133653702936,
  'MSE': 4.999545444626788,
  'RMSE': 2.2359663335181925,
  'R2': 0.5272421206982512},
 'day': {'MAE': 1.572460386651562,
  'MSE': 5.000290981377947,
  'RMSE': 2.2361330419673036,
  'R2': 0.5271716226145107},
 'month': {'MAE': 1.5723527039915655,
  'MSE': 4.999812183718297,
  'RMSE': 2.2360259801080793,
  'R2': 0.5272168978037649},
 'gender': {'MAE': 1.5724279695313215,
  'MSE': 5.000400835671181,
  'RMSE': 2.2361576052843817,
  'R2': 0.5271612347736006}}

In [214]:
dp3 = {'method': 'mean','percent': '1%','start_lat': {'MAE': 1.5723028869826516,
  'MSE': 4.999614575672232,
  'RMSE': 2.2359817923391576,
  'R2': 0.5272355836546738},
 'start_lon': {'MAE': 1.5723461241072976,
  'MSE': 4.9998601479731155,
  'RMSE': 2.2360367054172245,
  'R2': 0.5272123622955589},
 'end_lat': {'MAE': 1.5723121180253157,
  'MSE': 4.9995328416028055,
  'RMSE': 2.2359635152664734,
  'R2': 0.527243312442372},
 'end_lon': {'MAE': 1.5723241178832696,
  'MSE': 4.999559508289178,
  'RMSE': 2.2359694783894475,
  'R2': 0.5272407908359105},
 'hour': {'MAE': 1.5723609032674861,
  'MSE': 4.99991571126535,
  'RMSE': 2.236049129886316,
  'R2': 0.5272071082210645},
 'temp': {'MAE': 1.5723752525321657,
  'MSE': 4.999882767175554,
  'RMSE': 2.236041763289665,
  'R2': 0.5272102234198762},
 'feelslike': {'MAE': 1.5724278105372327,
  'MSE': 5.000154546519626,
  'RMSE': 2.2361025348851125,
  'R2': 0.5271845239182386},
 'dew': {'MAE': 1.572315296246298,
  'MSE': 4.999562631568011,
  'RMSE': 2.2359701768064824,
  'R2': 0.5272404954981256},
 'snowdepth': {'MAE': 1.5723456377105904,
  'MSE': 4.999717772784807,
  'RMSE': 2.2360048686853986,
  'R2': 0.5272258253179147},
 'winddir': {'MAE': 1.5723249450708132,
  'MSE': 4.999625176837524,
  'RMSE': 2.2359841629218944,
  'R2': 0.5272345812066559},
 'visibility': {'MAE': 1.5723140208138402,
  'MSE': 4.999591435042706,
  'RMSE': 2.2359766177316582,
  'R2': 0.5272377718365918},
 'sealevelpressure': {'MAE': 1.572317203040583,
  'MSE': 4.999574514624493,
  'RMSE': 2.235972834053333,
  'R2': 0.5272393718342556},
 'solarradiation': {'MAE': 1.572230587893635,
  'MSE': 4.999105407977542,
  'RMSE': 2.235867931693986,
  'R2': 0.5272837306396781},
 'dist': {'MAE': 1.582545994084682,
  'MSE': 5.063129278782301,
  'RMSE': 2.2501398353840814,
  'R2': 0.5212296223769204},
 'birthyear': {'MAE': 1.5723589109587466,
  'MSE': 4.999663752063589,
  'RMSE': 2.235992788911357,
  'R2': 0.5272309335266276}}

In [215]:
dp4 = {'method': 'sample','percent': '1%','start_lat': {'MAE': 1.5722983733789146,
  'MSE': 4.999546367423081,
  'RMSE': 2.235966539871087,
  'R2': 0.5272420334384744},
 'start_lon': {'MAE': 1.5723975220621318,
  'MSE': 5.000145791081451,
  'RMSE': 2.2361005771390183,
  'R2': 0.5271853518339821},
 'end_lat': {'MAE': 1.5723151521444365,
  'MSE': 4.9994699357634085,
  'RMSE': 2.2359494483917586,
  'R2': 0.5272492608293919},
 'end_lon': {'MAE': 1.5724606800432965,
  'MSE': 4.999861763928357,
  'RMSE': 2.236037066760826,
  'R2': 0.5272122094905527},
 'usertype': {'MAE': 1.572755840181274,
  'MSE': 5.0019820276404054,
  'RMSE': 2.2365111284409935,
  'R2': 0.5270117169883501},
 'hour': {'MAE': 1.5725154389696456,
  'MSE': 5.000864240041558,
  'RMSE': 2.2362612190979743,
  'R2': 0.5271174151764342},
 'temp': {'MAE': 1.572422111261905,
  'MSE': 5.000000882530477,
  'RMSE': 2.2360681748395947,
  'R2': 0.5271990544115484},
 'feelslike': {'MAE': 1.5724554845240328,
  'MSE': 5.000349793197187,
  'RMSE': 2.2361461922685617,
  'R2': 0.5271660613587426},
 'dew': {'MAE': 1.5722858176360284,
  'MSE': 4.999477133779158,
  'RMSE': 2.2359510580017528,
  'R2': 0.5272485801837816},
 'snowdepth': {'MAE': 1.5723470994448525,
  'MSE': 4.9996027077485214,
  'RMSE': 2.235979138486878,
  'R2': 0.5272367058875862},
 'winddir': {'MAE': 1.572322784390551,
  'MSE': 4.999620490632547,
  'RMSE': 2.2359831150150815,
  'R2': 0.5272350243350065},
 'sealevelpressure': {'MAE': 1.5723208234632442,
  'MSE': 4.999586442373806,
  'RMSE': 2.2359755012910596,
  'R2': 0.527238243944224},
 'visibility': {'MAE': 1.5723075241457622,
  'MSE': 4.999608324260587,
  'RMSE': 2.235980394426701,
  'R2': 0.5272361747892369},
 'solarradiation': {'MAE': 1.5722038457323078,
  'MSE': 4.998972156013488,
  'RMSE': 2.2358381327845467,
  'R2': 0.5272963309683754},
 'conditions': {'MAE': 1.5723255273509866,
  'MSE': 4.999645018082166,
  'RMSE': 2.235988599720975,
  'R2': 0.5272327050151413},
 'dist': {'MAE': 1.5907312960618991,
  'MSE': 5.118086690304741,
  'RMSE': 2.262318874585265,
  'R2': 0.5160328400672036},
 'birthyear': {'MAE': 1.5723310616625414,
  'MSE': 4.9995874875232,
  'RMSE': 2.235975735003222,
  'R2': 0.527238145114717},
 'holiday': {'MAE': 1.5723288774912807,
  'MSE': 4.999496299892584,
  'RMSE': 2.235955343894995,
  'R2': 0.5272467678327912},
 'day': {'MAE': 1.5724894326942176,
  'MSE': 5.000528524586657,
  'RMSE': 2.236186156067213,
  'R2': 0.5271491604877361},
 'month': {'MAE': 1.5723534153990522,
  'MSE': 4.999955707140307,
  'RMSE': 2.236058073293336,
  'R2': 0.5272033262042323},
 'gender': {'MAE': 1.5725722369748074,
  'MSE': 5.000967965628263,
  'RMSE': 2.236284410719769,
  'R2': 0.5271076068670701}}

In [216]:
d1 = pd.DataFrame(dp1)
d2 = pd.DataFrame(dp2)
d3 = pd.DataFrame(dp3)
d4 = pd.DataFrame(dp4)

In [217]:
data1 = [d1, d2,d3,d4]
df1 = pd.concat(data1, ignore_index=False, sort=False)

In [218]:
df1

,method,percent,start_lat,start_lon,end_lat,end_lon,usertype,hour,temp,feelslike,...,sealevelpressure,visibility,solarradiation,conditions,dist,birthyear,holiday,day,month,gender
MAE,drop,1%,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,...,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023
MSE,drop,1%,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,...,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234
RMSE,drop,1%,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,...,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015
R2,drop,1%,0.526629,0.526629,0.526629,0.526629,0.526629,0.526629,0.526629,0.526629,...,0.526629,0.526629,0.526629,0.526629,0.526629,0.526629,0.526629,0.526629,0.526629,0.526629
MAE,mode,1%,1.572305,1.572348,1.572317,1.572330,1.572420,1.572419,1.572422,1.572435,...,1.572316,1.572314,1.572250,1.572326,1.582974,1.572384,1.572313,1.572460,1.572353,1.572428
MSE,mode,1%,4.999627,4.999861,4.999552,4.999585,4.999829,5.000332,5.000115,5.000186,...,4.999573,4.999587,4.999208,4.999616,5.065700,4.999760,4.999545,5.000291,4.999812,5.000401
RMSE,mode,1%,2.235984,2.236037,2.235968,2.235975,2.236030,2.236142,2.236094,2.236110,...,2.235972,2.235976,2.235891,2.235982,2.250711,2.236014,2.235966,2.236133,2.236026,2.236158
R2,mode,1%,0.527234,0.527212,0.527242,0.527238,0.527215,0.527168,0.527188,0.527182,...,0.527240,0.527238,0.527274,0.527235,0.520987,0.527222,0.527242,0.527172,0.527217,0.527161
MAE,mean,1%,1.572303,1.572346,1.572312,1.572324,NaN,1.572361,1.572375,1.572428,...,1.572317,1.572314,1.572231,NaN,1.582546,1.572359,NaN,NaN,NaN,NaN
MSE,mean,1%,4.999615,4.999860,4.999533,4.999560,NaN,4.999916,4.999883,5.000155,...,4.999575,4.999591,4.999105,NaN,5.063129,4.999664,NaN,NaN,NaN,NaN
RMSE,mean,1%,2.235982,2.236037,2.235964,2.235969,NaN,2.236049,2.236042,2.236103,...,2.235973,2.235977,2.235868,NaN,2.250140,2.235993,NaN,NaN,NaN,NaN
R2,mean,1%,0.527236,0.527212,0.527243,0.527241,NaN,0.527207,0.527210,0.527185,...,0.527239,0.527238,0.527284,NaN,0.521230,0.527231,NaN,NaN,NaN,NaN
MAE,sample,1%,1.572298,1.572398,1.572315,1.572461,1.572756,1.572515,1.572422,1.572455,...,1.572321,1.572308,1.572204,1.572326,1.590731,1.572331,1.572329,1.572489,1.572353,1.572572
MSE,sample,1%,4.999546,5.000146,4.999470,4.999862,5.001982,5.000864,5.000001,5.000350,...,4.999586,4.999608,4.998972,4.999645,5.118087,4.999587,4.999496,5.000529,4.999956,5.000968
RMSE,sample,1%,2.235967,2.236101,2.235949,2.236037,2.236511,2.236261,2.236068,2.236146,...,2.235976,2.235980,2.235838,2.235989,2.262319,2.235976,2.235955,2.236186,2.236058,2.236284
R2,sample,1%,0.527242,0.527185,0.527249,0.527212,0.527012,0.527117,0.527199,0.527166,...,0.527238,0.527236,0.527296,0.527233,0.516033,0.527238,0.527247,0.527149,0.527203,0.527108

In [219]:
dd1 = {'method': 'drop','percent': '5%','start_lat': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'start_lon': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'end_lat': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'end_lon': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'usertype': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'hour': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'temp': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'feelslike': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'dew': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'snowdepth': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'winddir': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'sealevelpressure': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'visibility': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'solarradiation': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'conditions': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'dist': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'birthyear': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'holiday': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'day': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'month': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713},
 'gender': {'MAE': 1.57221692977683,
  'MSE': 5.003044094304209,
  'RMSE': 2.2367485541079954,
  'R2': 0.5261814122364713}}

In [220]:
dd2 = {'method': 'mode','percent': '5%','start_lat': {'MAE': 1.5722905984580589,
  'MSE': 4.9998369146695305,
  'RMSE': 2.236031510213917,
  'R2': 0.527214559240752},
 'start_lon': {'MAE': 1.5723721513544735,
  'MSE': 4.9999780986014235,
  'RMSE': 2.236063080192825,
  'R2': 0.5272012088638082},
 'end_lat': {'MAE': 1.5723099398113074,
  'MSE': 4.999841862808739,
  'RMSE': 2.2360326166692515,
  'R2': 0.5272140913438552},
 'end_lon': {'MAE': 1.5726237816482134,
  'MSE': 5.0003744961263275,
  'RMSE': 2.2361517158114133,
  'R2': 0.5271637254455035},
 'usertype': {'MAE': 1.5738518028291473,
  'MSE': 5.011245350651059,
  'RMSE': 2.238581102093703,
  'R2': 0.5261357755672135},
 'hour': {'MAE': 1.5730073666560653,
  'MSE': 5.0032957554188116,
  'RMSE': 2.2368048094142705,
  'R2': 0.5268874906631016},
 'temp': {'MAE': 1.5724724024106442,
  'MSE': 5.000529427936508,
  'RMSE': 2.236186358051696,
  'R2': 0.5271490750668184},
 'feelslike': {'MAE': 1.57247219039644,
  'MSE': 5.000336215551916,
  'RMSE': 2.236143156318914,
  'R2': 0.5271673452632206},
 'dew': {'MAE': 1.5722181572635152,
  'MSE': 4.999403369589363,
  'RMSE': 2.235934562904148,
  'R2': 0.5272555553382876},
 'snowdepth': {'MAE': 1.5723618130441364,
  'MSE': 4.999649418456597,
  'RMSE': 2.2359895837093244,
  'R2': 0.5272322889149764},
 'winddir': {'MAE': 1.57230744729644,
  'MSE': 4.9995271520023685,
  'RMSE': 2.23596224297334,
  'R2': 0.5272438504519703},
 'sealevelpressure': {'MAE': 1.5723225574268036,
  'MSE': 4.999571707210878,
  'RMSE': 2.2359722062697642,
  'R2': 0.5272396373037711},
 'visibility': {'MAE': 1.5723121610093846,
  'MSE': 4.999576274911657,
  'RMSE': 2.235973227682223,
  'R2': 0.5272392053811978},
 'solarradiation': {'MAE': 1.57219945410695,
  'MSE': 4.999608464256903,
  'RMSE': 2.2359804257320555,
  'R2': 0.527236161551161},
 'conditions': {'MAE': 1.5723230142658287,
  'MSE': 4.999705061436336,
  'RMSE': 2.236002026259443,
  'R2': 0.527227027305218},
 'dist': {'MAE': 1.6227709866226758,
  'MSE': 5.291706878711722,
  'RMSE': 2.300371030662602,
  'R2': 0.49961528511458897},
 'birthyear': {'MAE': 1.5725897197143255,
  'MSE': 5.001065184340124,
  'RMSE': 2.236306147275038,
  'R2': 0.5270984138489134},
 'holiday': {'MAE': 1.5723279978721534,
  'MSE': 4.999713863346161,
  'RMSE': 2.2360039944834984,
  'R2': 0.5272261949951071},
 'day': {'MAE': 1.572605956766945,
  'MSE': 5.001430669479489,
  'RMSE': 2.236387862039921,
  'R2': 0.5270638535111155},
 'month': {'MAE': 1.5724888364004703,
  'MSE': 5.000177780332149,
  'RMSE': 2.2361077300372068,
  'R2': 0.5271823269249203},
 'gender': {'MAE': 1.5730222667156113,
  'MSE': 5.002991206586691,
  'RMSE': 2.236736731621916,
  'R2': 0.5269162888531794}}

In [221]:
dd3 = {'method': 'mean','percent': '5%','start_lat': {'MAE': 1.5722749771969022,
  'MSE': 4.99976190726139,
  'RMSE': 2.2360147377111335,
  'R2': 0.527221651954199},
 'start_lon': {'MAE': 1.572408283143903,
  'MSE': 5.000041189486412,
  'RMSE': 2.236077187729979,
  'R2': 0.5271952429788451},
 'end_lat': {'MAE': 1.5722757377130143,
  'MSE': 4.999713074161806,
  'RMSE': 2.2360038180114556,
  'R2': 0.5272262696205158},
 'end_lon': {'MAE': 1.5725788061775683,
  'MSE': 5.000213078750087,
  'RMSE': 2.23611562284916,
  'R2': 0.5271789891004336},
 'hour': {'MAE': 1.572577536147564,
  'MSE': 5.001060542520806,
  'RMSE': 2.236305109442986,
  'R2': 0.5270988527801486},
 'temp': {'MAE': 1.5724445228548793,
  'MSE': 5.00038836530324,
  'RMSE': 2.236154816935366,
  'R2': 0.5271624139737433},
 'feelslike': {'MAE': 1.572456742799065,
  'MSE': 5.000289891402653,
  'RMSE': 2.2361327982484966,
  'R2': 0.5271717256827624},
 'dew': {'MAE': 1.5722703842567702,
  'MSE': 4.999404189211033,
  'RMSE': 2.235934746188053,
  'R2': 0.5272554778347212},
 'snowdepth': {'MAE': 1.572352272887785,
  'MSE': 4.999614098457158,
  'RMSE': 2.235981685626508,
  'R2': 0.5272356287802134},
 'winddir': {'MAE': 1.5723077722816274,
  'MSE': 4.999525538263421,
  'RMSE': 2.2359618821132483,
  'R2': 0.5272440030474035},
 'visibility': {'MAE': 1.572315485214342,
  'MSE': 4.999595727463775,
  'RMSE': 2.235977577585199,
  'R2': 0.5272373659445155},
 'sealevelpressure': {'MAE': 1.5723288132594189,
  'MSE': 4.999586583181605,
  'RMSE': 2.235975532777943,
  'R2': 0.5272382306294142},
 'solarradiation': {'MAE': 1.5720590740814093,
  'MSE': 4.998963573705707,
  'RMSE': 2.2358362135240823,
  'R2': 0.527297142512879},
 'dist': {'MAE': 1.6196666743174344,
  'MSE': 5.278231315695791,
  'RMSE': 2.2974401658575987,
  'R2': 0.5008895366769296},
 'birthyear': {'MAE': 1.5724467169176395,
  'MSE': 5.000503246287972,
  'RMSE': 2.236180503959368,
  'R2': 0.5271515508080185}}

In [222]:
dd4 = {'method': 'sample','percent': '5%','start_lat': {'MAE': 1.5722497081781581,
  'MSE': 4.999946099221386,
  'RMSE': 2.2360559248868053,
  'R2': 0.5272042347307021},
 'start_lon': {'MAE': 1.5726021562608021,
  'MSE': 5.000488891245084,
  'RMSE': 2.2361772942334164,
  'R2': 0.5271529082233491},
 'end_lat': {'MAE': 1.5722990098325715,
  'MSE': 5.00010224805974,
  'RMSE': 2.2360908407441187,
  'R2': 0.5271894692696231},
 'end_lon': {'MAE': 1.5726064637800512,
  'MSE': 5.000956474305045,
  'RMSE': 2.2362818414289927,
  'R2': 0.5271086934885751},
 'usertype': {'MAE': 1.5751892105740941,
  'MSE': 5.018800988344268,
  'RMSE': 2.2402680617158897,
  'R2': 0.5254213131641459},
 'hour': {'MAE': 1.572931757129256,
  'MSE': 5.002814394561246,
  'RMSE': 2.236697206722726,
  'R2': 0.5269330082287927},
 'temp': {'MAE': 1.5724927645228082,
  'MSE': 5.000577962271786,
  'RMSE': 2.2361972100581347,
  'R2': 0.5271444856517059},
 'feelslike': {'MAE': 1.57242716873781,
  'MSE': 5.000206470697878,
  'RMSE': 2.2361141452747617,
  'R2': 0.5271796139589898},
 'dew': {'MAE': 1.5722651211854155,
  'MSE': 4.9993465005867455,
  'RMSE': 2.235921845813656,
  'R2': 0.5272609328809809},
 'snowdepth': {'MAE': 1.5724008251080888,
  'MSE': 4.999733976139731,
  'RMSE': 2.236008491965031,
  'R2': 0.5272242931258793},
 'winddir': {'MAE': 1.5723071102855,
  'MSE': 4.999532827003442,
  'RMSE': 2.235963512001804,
  'R2': 0.5272433138228902},
 'sealevelpressure': {'MAE': 1.5723099774702032,
  'MSE': 4.9995363379537965,
  'RMSE': 2.235964297110711,
  'R2': 0.5272429818268194},
 'visibility': {'MAE': 1.5723104353748265,
  'MSE': 4.999586421802136,
  'RMSE': 2.2359754966909042,
  'R2': 0.5272382458894846},
 'solarradiation': {'MAE': 1.5721685571762614,
  'MSE': 4.999649372230784,
  'RMSE': 2.2359895733725557,
  'R2': 0.5272322932860973},
 'conditions': {'MAE': 1.57228718901748,
  'MSE': 4.999594414457041,
  'RMSE': 2.2359772839760788,
  'R2': 0.5272374901026586},
 'dist': {'MAE': 1.6595729221877118,
  'MSE': 5.550357563426786,
  'RMSE': 2.3559196852666235,
  'R2': 0.47515723176950786},
 'birthyear': {'MAE': 1.5724866903580963,
  'MSE': 5.000730168746609,
  'RMSE': 2.2362312422347133,
  'R2': 0.5271300929812021},
 'holiday': {'MAE': 1.5723153586681418,
  'MSE': 4.999642691188128,
  'RMSE': 2.2359880793931186,
  'R2': 0.5272329250466428},
 'day': {'MAE': 1.5727350236587958,
  'MSE': 5.002956145385867,
  'RMSE': 2.236728894029374,
  'R2': 0.5269196042463749},
 'month': {'MAE': 1.5724353596075624,
  'MSE': 5.000072960482787,
  'RMSE': 2.236084291900193,
  'R2': 0.5271922387079497},
 'gender': {'MAE': 1.573175467408024,
  'MSE': 5.003772467174186,
  'RMSE': 2.23691136775112,
  'R2': 0.5268424127173152}}

In [223]:
d11 = pd.DataFrame(dd1)
d12 = pd.DataFrame(dd2)
d13 = pd.DataFrame(dd3)
d14 = pd.DataFrame(dd4)

In [224]:
data2 = [d11, d12,d13,d14]
df2 = pd.concat(data2, ignore_index=False, sort=False)

In [225]:
df2

,method,percent,start_lat,start_lon,end_lat,end_lon,usertype,hour,temp,feelslike,...,sealevelpressure,visibility,solarradiation,conditions,dist,birthyear,holiday,day,month,gender
MAE,drop,5%,1.572217,1.572217,1.572217,1.572217,1.572217,1.572217,1.572217,1.572217,...,1.572217,1.572217,1.572217,1.572217,1.572217,1.572217,1.572217,1.572217,1.572217,1.572217
MSE,drop,5%,5.003044,5.003044,5.003044,5.003044,5.003044,5.003044,5.003044,5.003044,...,5.003044,5.003044,5.003044,5.003044,5.003044,5.003044,5.003044,5.003044,5.003044,5.003044
RMSE,drop,5%,2.236749,2.236749,2.236749,2.236749,2.236749,2.236749,2.236749,2.236749,...,2.236749,2.236749,2.236749,2.236749,2.236749,2.236749,2.236749,2.236749,2.236749,2.236749
R2,drop,5%,0.526181,0.526181,0.526181,0.526181,0.526181,0.526181,0.526181,0.526181,...,0.526181,0.526181,0.526181,0.526181,0.526181,0.526181,0.526181,0.526181,0.526181,0.526181
MAE,mode,5%,1.572291,1.572372,1.572310,1.572624,1.573852,1.573007,1.572472,1.572472,...,1.572323,1.572312,1.572199,1.572323,1.622771,1.572590,1.572328,1.572606,1.572489,1.573022
MSE,mode,5%,4.999837,4.999978,4.999842,5.000374,5.011245,5.003296,5.000529,5.000336,...,4.999572,4.999576,4.999608,4.999705,5.291707,5.001065,4.999714,5.001431,5.000178,5.002991
RMSE,mode,5%,2.236032,2.236063,2.236033,2.236152,2.238581,2.236805,2.236186,2.236143,...,2.235972,2.235973,2.235980,2.236002,2.300371,2.236306,2.236004,2.236388,2.236108,2.236737
R2,mode,5%,0.527215,0.527201,0.527214,0.527164,0.526136,0.526887,0.527149,0.527167,...,0.527240,0.527239,0.527236,0.527227,0.499615,0.527098,0.527226,0.527064,0.527182,0.526916
MAE,mean,5%,1.572275,1.572408,1.572276,1.572579,NaN,1.572578,1.572445,1.572457,...,1.572329,1.572315,1.572059,NaN,1.619667,1.572447,NaN,NaN,NaN,NaN
MSE,mean,5%,4.999762,5.000041,4.999713,5.000213,NaN,5.001061,5.000388,5.000290,...,4.999587,4.999596,4.998964,NaN,5.278231,5.000503,NaN,NaN,NaN,NaN
RMSE,mean,5%,2.236015,2.236077,2.236004,2.236116,NaN,2.236305,2.236155,2.236133,...,2.235976,2.235978,2.235836,NaN,2.297440,2.236181,NaN,NaN,NaN,NaN
R2,mean,5%,0.527222,0.527195,0.527226,0.527179,NaN,0.527099,0.527162,0.527172,...,0.527238,0.527237,0.527297,NaN,0.500890,0.527152,NaN,NaN,NaN,NaN
MAE,sample,5%,1.572250,1.572602,1.572299,1.572606,1.575189,1.572932,1.572493,1.572427,...,1.572310,1.572310,1.572169,1.572287,1.659573,1.572487,1.572315,1.572735,1.572435,1.573175
MSE,sample,5%,4.999946,5.000489,5.000102,5.000956,5.018801,5.002814,5.000578,5.000206,...,4.999536,4.999586,4.999649,4.999594,5.550358,5.000730,4.999643,5.002956,5.000073,5.003772
RMSE,sample,5%,2.236056,2.236177,2.236091,2.236282,2.240268,2.236697,2.236197,2.236114,...,2.235964,2.235975,2.235990,2.235977,2.355920,2.236231,2.235988,2.236729,2.236084,2.236911
R2,sample,5%,0.527204,0.527153,0.527189,0.527109,0.525421,0.526933,0.527144,0.527180,...,0.527243,0.527238,0.527232,0.527237,0.475157,0.527130,0.527233,0.526920,0.527192,0.526842

In [226]:
dk1= {'method': 'drop','percent': '10%','start_lat': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'start_lon': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'end_lat': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'end_lon': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'usertype': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'hour': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'temp': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'feelslike': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'dew': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'snowdepth': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'winddir': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'sealevelpressure': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'visibility': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'solarradiation': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'conditions': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'dist': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'birthyear': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'holiday': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'day': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'month': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183},
 'gender': {'MAE': 1.5721830060322195,
  'MSE': 5.013337711560819,
  'RMSE': 2.2390483941980395,
  'R2': 0.5246907136672183}}

In [227]:
dk2= {'method': 'mode','percent': '10%','start_lat': {'MAE': 1.5722040548463578,
  'MSE': 4.99969795196476,
  'RMSE': 2.236000436485816,
  'R2': 0.527227699578076},
 'start_lon': {'MAE': 1.5728486211254735,
  'MSE': 5.002883184954267,
  'RMSE': 2.236712584342089,
  'R2': 0.5269265033973674},
 'end_lat': {'MAE': 1.5722304094925525,
  'MSE': 4.999740029191904,
  'RMSE': 2.236009845504242,
  'R2': 0.527223720748222},
 'end_lon': {'MAE': 1.5727225964350673,
  'MSE': 5.000551268379016,
  'RMSE': 2.2361912414592395,
  'R2': 0.527147009830809},
 'usertype': {'MAE': 1.5756771486233472,
  'MSE': 5.021445275137298,
  'RMSE': 2.240858155961081,
  'R2': 0.5251712689490499},
 'hour': {'MAE': 1.5730260790691732,
  'MSE': 5.003754451295777,
  'RMSE': 2.236907340793484,
  'R2': 0.5268441163018841},
 'temp': {'MAE': 1.572541767719938,
  'MSE': 5.00079249478944,
  'RMSE': 2.2362451777006562,
  'R2': 0.5271241994198452},
 'feelslike': {'MAE': 1.5724419588674323,
  'MSE': 5.000249090621296,
  'RMSE': 2.2361236751622875,
  'R2': 0.5271755838116825},
 'dew': {'MAE': 1.5722769409958528,
  'MSE': 4.999661948850185,
  'RMSE': 2.235992385686987,
  'R2': 0.5272311040387982},
 'snowdepth': {'MAE': 1.5723568952507707,
  'MSE': 4.999423073903106,
  'RMSE': 2.235938969181204,
  'R2': 0.5272536920949825},
 'winddir': {'MAE': 1.5723039900103097,
  'MSE': 4.999503351057162,
  'RMSE': 2.2359569206621943,
  'R2': 0.5272461010734529},
 'sealevelpressure': {'MAE': 1.5723275788410143,
  'MSE': 4.999564984224199,
  'RMSE': 2.2359707028993467,
  'R2': 0.5272402730305507},
 'visibility': {'MAE': 1.5723384386786583,
  'MSE': 4.999594460628738,
  'RMSE': 2.2359772943008025,
  'R2': 0.5272374857366551},
 'solarradiation': {'MAE': 1.5720789114548304,
  'MSE': 4.99945719393612,
  'RMSE': 2.2359465990797096,
  'R2': 0.5272504656987774},
 'conditions': {'MAE': 1.5722852859767256,
  'MSE': 4.999582665815695,
  'RMSE': 2.235974656791909,
  'R2': 0.52723860105621},
 'dist': {'MAE': 1.6708662069600082,
  'MSE': 5.566838317909328,
  'RMSE': 2.359414825313541,
  'R2': 0.4735988087839077},
 'birthyear': {'MAE': 1.5725531137027131,
  'MSE': 5.000922132242666,
  'RMSE': 2.236274163031596,
  'R2': 0.5271119408799152},
 'holiday': {'MAE': 1.5723477729580553,
  'MSE': 5.000499461772859,
  'RMSE': 2.236179657758486,
  'R2': 0.5271519086724201},
 'day': {'MAE': 1.5727846931068008,
  'MSE': 5.002639592758663,
  'RMSE': 2.236658130506015,
  'R2': 0.5269495375173856},
 'month': {'MAE': 1.572423417772608,
  'MSE': 4.999911220611595,
  'RMSE': 2.2360481257369202,
  'R2': 0.5272075328580581},
 'gender': {'MAE': 1.5731820250186201,
  'MSE': 5.004679519657329,
  'RMSE': 2.237114105193861,
  'R2': 0.5267566416781087}}

In [228]:
dk3= {'method': 'mean','percent': '10%','start_lat': {'MAE': 1.5722362594683228,
  'MSE': 4.999711471568887,
  'RMSE': 2.2360034596504734,
  'R2': 0.5272264211619786},
 'start_lon': {'MAE': 1.572798121647502,
  'MSE': 5.002659646341988,
  'RMSE': 2.2366626134359175,
  'R2': 0.5269476412470886},
 'end_lat': {'MAE': 1.572254466669696,
  'MSE': 4.999736114555237,
  'RMSE': 2.236008970141944,
  'R2': 0.5272240909169403},
 'end_lon': {'MAE': 1.5727338671514686,
  'MSE': 5.000584346559199,
  'RMSE': 2.2361986375452427,
  'R2': 0.5271438819523873},
 'hour': {'MAE': 1.5726545300386487,
  'MSE': 5.001261216296576,
  'RMSE': 2.236349976255187,
  'R2': 0.52707987703331},
 'temp': {'MAE': 1.5725346409789673,
  'MSE': 5.0007240880455885,
  'RMSE': 2.236229882647486,
  'R2': 0.527130667973339},
 'feelslike': {'MAE': 1.5724659132057233,
  'MSE': 5.00035041131011,
  'RMSE': 2.236146330477974,
  'R2': 0.527166002909878},
 'dew': {'MAE': 1.5722644664869885,
  'MSE': 4.999479622906542,
  'RMSE': 2.2359516146165914,
  'R2': 0.5272483448114669},
 'snowdepth': {'MAE': 1.5723563572933363,
  'MSE': 4.999449545531506,
  'RMSE': 2.2359448887509514,
  'R2': 0.5272511889332366},
 'winddir': {'MAE': 1.5723060165639842,
  'MSE': 4.99951352002339,
  'RMSE': 2.2359591946239514,
  'R2': 0.527245139494253},
 'visibility': {'MAE': 1.5723294838605553,
  'MSE': 4.9995673285636855,
  'RMSE': 2.235971227132336,
  'R2': 0.5272400513494047},
 'sealevelpressure': {'MAE': 1.5723188546819786,
  'MSE': 4.99955177888708,
  'RMSE': 2.2359677499657904,
  'R2': 0.5272415217295057},
 'solarradiation': {'MAE': 1.5720117079474882,
  'MSE': 4.998929597194642,
  'RMSE': 2.2358286153447993,
  'R2': 0.5273003553376236},
 'dist': {'MAE': 1.666058984234458,
  'MSE': 5.546604157949029,
  'RMSE': 2.3551229602611046,
  'R2': 0.4755121544386739},
 'birthyear': {'MAE': 1.5724482039539858,
  'MSE': 5.000470384452982,
  'RMSE': 2.2361731561873697,
  'R2': 0.5271546582288014}}

In [229]:
dk4= {'method': 'sample','percent': '10%','start_lat': {'MAE': 1.5721700731898758,
  'MSE': 4.999847797058164,
  'RMSE': 2.2360339436283527,
  'R2': 0.5272135302002063},
 'start_lon': {'MAE': 1.573066088083224,
  'MSE': 5.0040700215225495,
  'RMSE': 2.2369778768513893,
  'R2': 0.5268142759268275},
 'end_lat': {'MAE': 1.572264133773408,
  'MSE': 5.000405173016989,
  'RMSE': 2.2361585751053052,
  'R2': 0.5271608246334331},
 'end_lon': {'MAE': 1.5730148975356515,
  'MSE': 5.0012658589872325,
  'RMSE': 2.23635101426123,
  'R2': 0.527079438019681},
 'usertype': {'MAE': 1.5784133639045246,
  'MSE': 5.035210871002452,
  'RMSE': 2.243927554758052,
  'R2': 0.5238695918304772},
 'hour': {'MAE': 1.5732194712261443,
  'MSE': 5.003413330880514,
  'RMSE': 2.2368310912718723,
  'R2': 0.5268763727071697},
 'temp': {'MAE': 1.5725631169449839,
  'MSE': 5.0009002819574855,
  'RMSE': 2.2362692776044404,
  'R2': 0.5271140070466495},
 'feelslike': {'MAE': 1.5724558949565184,
  'MSE': 5.000288520207748,
  'RMSE': 2.236132491648862,
  'R2': 0.527171855343189},
 'dew': {'MAE': 1.5722487129306042,
  'MSE': 4.999551987097205,
  'RMSE': 2.235967796525076,
  'R2': 0.5272415020411203},
 'snowdepth': {'MAE': 1.572335649274405,
  'MSE': 4.999207127079255,
  'RMSE': 2.2358906786959096,
  'R2': 0.527274112063881},
 'winddir': {'MAE': 1.5722943372915064,
  'MSE': 4.999463136325786,
  'RMSE': 2.235947927910171,
  'R2': 0.527249903785386},
 'sealevelpressure': {'MAE': 1.5723197065404662,
  'MSE': 4.999488425358085,
  'RMSE': 2.23595358300616,
  'R2': 0.5272475124501312},
 'visibility': {'MAE': 1.5723186684559378,
  'MSE': 4.999524245114348,
  'RMSE': 2.2359615929425862,
  'R2': 0.5272441253278028},
 'solarradiation': {'MAE': 1.572130031972681,
  'MSE': 5.00007721133236,
  'RMSE': 2.2360852424119164,
  'R2': 0.5271918367468812},
 'conditions': {'MAE': 1.572296415282547,
  'MSE': 4.999795837795981,
  'RMSE': 2.2360223249770965,
  'R2': 0.5272184434769975},
 'dist': {'MAE': 1.7346268652241954,
  'MSE': 5.985066828916816,
  'RMSE': 2.446439622986191,
  'R2': 0.4340510486690503},
 'birthyear': {'MAE': 1.5727194270934317,
  'MSE': 5.0017571842369355,
  'RMSE': 2.2364608613246366,
  'R2': 0.5270329782193512},
 'holiday': {'MAE': 1.5722828672571525,
  'MSE': 5.000399336406182,
  'RMSE': 2.2361572700519483,
  'R2': 0.5271613765443574},
 'day': {'MAE': 1.5731963801841125,
  'MSE': 5.004601463363347,
  'RMSE': 2.2370966593697617,
  'R2': 0.5267640226947268},
 'month': {'MAE': 1.5725025795861014,
  'MSE': 4.999752510605333,
  'RMSE': 2.236012636503947,
  'R2': 0.527222540503616},
 'gender': {'MAE': 1.5733926104505658,
  'MSE': 5.00755694034017,
  'RMSE': 2.2377571227325297,
  'R2': 0.5264845522821935}}

In [230]:
da1 = pd.DataFrame(dk1)
da2 = pd.DataFrame(dk2)
da3 = pd.DataFrame(dk3)
da4 = pd.DataFrame(dk4)

In [231]:
data3 = [da1, da2,da3,da4]
df3 = pd.concat(data3, ignore_index=False, sort=False)

In [232]:
df3

,method,percent,start_lat,start_lon,end_lat,end_lon,usertype,hour,temp,feelslike,...,sealevelpressure,visibility,solarradiation,conditions,dist,birthyear,holiday,day,month,gender
MAE,drop,10%,1.572183,1.572183,1.572183,1.572183,1.572183,1.572183,1.572183,1.572183,...,1.572183,1.572183,1.572183,1.572183,1.572183,1.572183,1.572183,1.572183,1.572183,1.572183
MSE,drop,10%,5.013338,5.013338,5.013338,5.013338,5.013338,5.013338,5.013338,5.013338,...,5.013338,5.013338,5.013338,5.013338,5.013338,5.013338,5.013338,5.013338,5.013338,5.013338
RMSE,drop,10%,2.239048,2.239048,2.239048,2.239048,2.239048,2.239048,2.239048,2.239048,...,2.239048,2.239048,2.239048,2.239048,2.239048,2.239048,2.239048,2.239048,2.239048,2.239048
R2,drop,10%,0.524691,0.524691,0.524691,0.524691,0.524691,0.524691,0.524691,0.524691,...,0.524691,0.524691,0.524691,0.524691,0.524691,0.524691,0.524691,0.524691,0.524691,0.524691
MAE,mode,10%,1.572204,1.572849,1.572230,1.572723,1.575677,1.573026,1.572542,1.572442,...,1.572328,1.572338,1.572079,1.572285,1.670866,1.572553,1.572348,1.572785,1.572423,1.573182
MSE,mode,10%,4.999698,5.002883,4.999740,5.000551,5.021445,5.003754,5.000792,5.000249,...,4.999565,4.999594,4.999457,4.999583,5.566838,5.000922,5.000499,5.002640,4.999911,5.004680
RMSE,mode,10%,2.236000,2.236713,2.236010,2.236191,2.240858,2.236907,2.236245,2.236124,...,2.235971,2.235977,2.235947,2.235975,2.359415,2.236274,2.236180,2.236658,2.236048,2.237114
R2,mode,10%,0.527228,0.526927,0.527224,0.527147,0.525171,0.526844,0.527124,0.527176,...,0.527240,0.527237,0.527250,0.527239,0.473599,0.527112,0.527152,0.526950,0.527208,0.526757
MAE,mean,10%,1.572236,1.572798,1.572254,1.572734,NaN,1.572655,1.572535,1.572466,...,1.572319,1.572329,1.572012,NaN,1.666059,1.572448,NaN,NaN,NaN,NaN
MSE,mean,10%,4.999711,5.002660,4.999736,5.000584,NaN,5.001261,5.000724,5.000350,...,4.999552,4.999567,4.998930,NaN,5.546604,5.000470,NaN,NaN,NaN,NaN
RMSE,mean,10%,2.236003,2.236663,2.236009,2.236199,NaN,2.236350,2.236230,2.236146,...,2.235968,2.235971,2.235829,NaN,2.355123,2.236173,NaN,NaN,NaN,NaN
R2,mean,10%,0.527226,0.526948,0.527224,0.527144,NaN,0.527080,0.527131,0.527166,...,0.527242,0.527240,0.527300,NaN,0.475512,0.527155,NaN,NaN,NaN,NaN
MAE,sample,10%,1.572170,1.573066,1.572264,1.573015,1.578413,1.573219,1.572563,1.572456,...,1.572320,1.572319,1.572130,1.572296,1.734627,1.572719,1.572283,1.573196,1.572503,1.573393
MSE,sample,10%,4.999848,5.004070,5.000405,5.001266,5.035211,5.003413,5.000900,5.000289,...,4.999488,4.999524,5.000077,4.999796,5.985067,5.001757,5.000399,5.004601,4.999753,5.007557
RMSE,sample,10%,2.236034,2.236978,2.236159,2.236351,2.243928,2.236831,2.236269,2.236132,...,2.235954,2.235962,2.236085,2.236022,2.446440,2.236461,2.236157,2.237097,2.236013,2.237757
R2,sample,10%,0.527214,0.526814,0.527161,0.527079,0.523870,0.526876,0.527114,0.527172,...,0.527248,0.527244,0.527192,0.527218,0.434051,0.527033,0.527161,0.526764,0.527223,0.526485

In [233]:
ds1= {'method': 'drop','percent': '20%','start_lat': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'start_lon': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'end_lat': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'end_lon': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'usertype': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'hour': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'temp': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'feelslike': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'dew': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'snowdepth': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'winddir': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'sealevelpressure': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'visibility': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'solarradiation': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'conditions': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'dist': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'birthyear': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'holiday': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'day': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'month': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994},
 'gender': {'MAE': 1.5707629260207865,
  'MSE': 4.985157143314904,
  'RMSE': 2.2327465470390733,
  'R2': 0.5282643786583994}}

In [234]:
ds2= {'method': 'mode','percent': '20%','start_lat': {'MAE': 1.5722130252690756,
  'MSE': 5.000209201674977,
  'RMSE': 2.236114755927114,
  'R2': 0.5271793557173245},
 'start_lon': {'MAE': 1.5731200523922648,
  'MSE': 5.004431807531456,
  'RMSE': 2.2370587402952693,
  'R2': 0.5267800653794436},
 'end_lat': {'MAE': 1.57225520655082,
  'MSE': 5.000424067378656,
  'RMSE': 2.236162799837851,
  'R2': 0.5271590379793359},
 'end_lon': {'MAE': 1.5733007420152174,
  'MSE': 5.001869650722917,
  'RMSE': 2.2364860050362303,
  'R2': 0.5270223433690446},
 'usertype': {'MAE': 1.5780241854409498,
  'MSE': 5.032746222635772,
  'RMSE': 2.243378305733514,
  'R2': 0.5241026494050028},
 'hour': {'MAE': 1.5737265209413012,
  'MSE': 5.007616314859015,
  'RMSE': 2.2377703892175833,
  'R2': 0.5264789378174537},
 'temp': {'MAE': 1.5726022149666066,
  'MSE': 5.000988054240213,
  'RMSE': 2.2362889022307053,
  'R2': 0.5271057072844605},
 'feelslike': {'MAE': 1.5724426255795068,
  'MSE': 5.00025727555317,
  'RMSE': 2.2361255053223577,
  'R2': 0.5271748098431134},
 'dew': {'MAE': 1.5722636272535817,
  'MSE': 4.999660253056762,
  'RMSE': 2.235992006483199,
  'R2': 0.5272312643933166},
 'snowdepth': {'MAE': 1.5723695673745328,
  'MSE': 4.999420206727939,
  'RMSE': 2.2359383280242637,
  'R2': 0.5272539632155606},
 'winddir': {'MAE': 1.5723114712468707,
  'MSE': 4.999563756613964,
  'RMSE': 2.2359704283853943,
  'R2': 0.5272403891135862},
 'sealevelpressure': {'MAE': 1.5722945339408252,
  'MSE': 4.99957603571532,
  'RMSE': 2.2359731741940285,
  'R2': 0.5272392279996447},
 'visibility': {'MAE': 1.572302910220217,
  'MSE': 4.99954896640666,
  'RMSE': 2.235967121047772,
  'R2': 0.5272417876781391},
 'solarradiation': {'MAE': 1.5722644032287567,
  'MSE': 5.001483105745439,
  'RMSE': 2.2363995854375935,
  'R2': 0.5270588951287658},
 'conditions': {'MAE': 1.5723138821944485,
  'MSE': 4.999660173419373,
  'RMSE': 2.2359919886751323,
  'R2': 0.5272312719238419},
 'dist': {'MAE': 1.7624427447319446,
  'MSE': 6.041492914981203,
  'RMSE': 2.4579448559683357,
  'R2': 0.4287153882414074},
 'birthyear': {'MAE': 1.5729606630920117,
  'MSE': 5.00270101714809,
  'RMSE': 2.236671861750867,
  'R2': 0.52694372921653},
 'holiday': {'MAE': 1.5724036547088662,
  'MSE': 5.0010637239064515,
  'RMSE': 2.236305820746897,
  'R2': 0.5270985519477733},
 'day': {'MAE': 1.5731920898107985,
  'MSE': 5.006786076258301,
  'RMSE': 2.2375848757663475,
  'R2': 0.5265574453226931},
 'month': {'MAE': 1.5724516125564492,
  'MSE': 5.000211161716856,
  'RMSE': 2.2361151941965907,
  'R2': 0.5271791703754265},
 'gender': {'MAE': 1.5740749257183717,
  'MSE': 5.008699910189532,
  'RMSE': 2.238012491070935,
  'R2': 0.5263764728561587}}

In [235]:
ds3= {'method': 'mean','percent': '20%','start_lat': {'MAE': 1.5722550153708958,
  'MSE': 5.0002226217131,
  'RMSE': 2.2361177566740755,
  'R2': 0.5271780867162057},
 'start_lon': {'MAE': 1.573040903172298,
  'MSE': 5.004207862632298,
  'RMSE': 2.23700868631132,
  'R2': 0.5268012416477221},
 'end_lat': {'MAE': 1.57228429465235,
  'MSE': 5.000370928083709,
  'RMSE': 2.2361509180025636,
  'R2': 0.5271640628402288},
 'end_lon': {'MAE': 1.573303497299732,
  'MSE': 5.001814060824874,
  'RMSE': 2.236473577045987,
  'R2': 0.5270275999593889},
 'hour': {'MAE': 1.5732184751717613,
  'MSE': 5.003379389861619,
  'RMSE': 2.23682350440566,
  'R2': 0.5268795821757688},
 'temp': {'MAE': 1.5725953614455166,
  'MSE': 5.000956942319607,
  'RMSE': 2.236281946070219,
  'R2': 0.5271086492330375},
 'feelslike': {'MAE': 1.5724520390696803,
  'MSE': 5.000300389737768,
  'RMSE': 2.2361351456783125,
  'R2': 0.5271707329583837},
 'dew': {'MAE': 1.5722639380866297,
  'MSE': 4.9995794149944075,
  'RMSE': 2.2359739298557146,
  'R2': 0.5272389084544316},
 'snowdepth': {'MAE': 1.5723709278154505,
  'MSE': 4.999432105899714,
  'RMSE': 2.235940988912658,
  'R2': 0.5272528380278259},
 'winddir': {'MAE': 1.5723125837594087,
  'MSE': 4.999569004442684,
  'RMSE': 2.235971601886456,
  'R2': 0.5272398928779976},
 'visibility': {'MAE': 1.5722875218587182,
  'MSE': 4.999532782440361,
  'RMSE': 2.2359635020367308,
  'R2': 0.527243318036783},
 'sealevelpressure': {'MAE': 1.572285613160014,
  'MSE': 4.999564740672481,
  'RMSE': 2.2359706484371573,
  'R2': 0.5272402960608431},
 'solarradiation': {'MAE': 1.5721930304174092,
  'MSE': 5.000728034956508,
  'RMSE': 2.2362307651395255,
  'R2': 0.5271302947527619},
 'dist': {'MAE': 1.7533858963883933,
  'MSE': 6.006748649575869,
  'RMSE': 2.4508669179651243,
  'R2': 0.43200081196899365},
 'birthyear': {'MAE': 1.5728135145675897,
  'MSE': 5.0018025867235965,
  'RMSE': 2.2364710118227773,
  'R2': 0.527028684952384}}

In [236]:
ds4= {'method': 'sample','percent': '20%','start_lat': {'MAE': 1.5721858537040991,
  'MSE': 5.000123563157097,
  'RMSE': 2.2360956068909705,
  'R2': 0.5271874537103416},
 'start_lon': {'MAE': 1.5735238600154633,
  'MSE': 5.006689839171069,
  'RMSE': 2.2375633709843994,
  'R2': 0.5265665455182555},
 'end_lat': {'MAE': 1.5722405149892742,
  'MSE': 5.001055386088714,
  'RMSE': 2.2363039565516836,
  'R2': 0.5270993403732563},
 'end_lon': {'MAE': 1.5737372496144444,
  'MSE': 5.003683882167789,
  'RMSE': 2.23689156692223,
  'R2': 0.5268507893307945},
 'usertype': {'MAE': 1.5826559045403263,
  'MSE': 5.055900137053465,
  'RMSE': 2.2485328854729842,
  'R2': 0.5219132112653002},
 'hour': {'MAE': 1.5744080137214291,
  'MSE': 5.009882932063067,
  'RMSE': 2.2382767773586596,
  'R2': 0.5262646061038121},
 'temp': {'MAE': 1.572625778070869,
  'MSE': 5.001133459931957,
  'RMSE': 2.2363214124834463,
  'R2': 0.5270919576971773},
 'feelslike': {'MAE': 1.5724446142813107,
  'MSE': 5.000302598539022,
  'RMSE': 2.2361356395663976,
  'R2': 0.5271705240937562},
 'dew': {'MAE': 1.572244288898598,
  'MSE': 4.999600999550195,
  'RMSE': 2.2359787565069116,
  'R2': 0.5272368674151146},
 'snowdepth': {'MAE': 1.5724165783252906,
  'MSE': 4.999148954176155,
  'RMSE': 2.2358776697700065,
  'R2': 0.5272796129036287},
 'winddir': {'MAE': 1.572291487276393,
  'MSE': 4.999471108802876,
  'RMSE': 2.2359497107052464,
  'R2': 0.5272491499065777},
 'sealevelpressure': {'MAE': 1.5722616070900493,
  'MSE': 4.999459156313326,
  'RMSE': 2.2359470379043698,
  'R2': 0.5272502801360506},
 'visibility': {'MAE': 1.5722772717203108,
  'MSE': 4.999349645476142,
  'RMSE': 2.2359225490781522,
  'R2': 0.5272606354996972},
 'solarradiation': {'MAE': 1.5722917330554236,
  'MSE': 5.001869983522228,
  'RMSE': 2.236486079438508,
  'R2': 0.5270223118994845},
 'conditions': {'MAE': 1.5723211479235168,
  'MSE': 4.999889040204275,
  'RMSE': 2.236043165997534,
  'R2': 0.5272096302411986},
 'dist': {'MAE': 1.8857535300594146,
  'MSE': 6.783893502266793,
  'RMSE': 2.6045908512215106,
  'R2': 0.35851386069759505},
 'birthyear': {'MAE': 1.5732906552661152,
  'MSE': 5.003966863837619,
  'RMSE': 2.2369548193554603,
  'R2': 0.5268240305353018},
 'holiday': {'MAE': 1.5723676760276812,
  'MSE': 5.000252884478791,
  'RMSE': 2.236124523473322,
  'R2': 0.5271752250638637},
 'day': {'MAE': 1.573793095854583,
  'MSE': 5.010242868531359,
  'RMSE': 2.2383571807312967,
  'R2': 0.5262305704493075},
 'month': {'MAE': 1.572623207798425,
  'MSE': 5.000603990964082,
  'RMSE': 2.2362030299067395,
  'R2': 0.5271420243740743},
 'gender': {'MAE': 1.5746554872755103,
  'MSE': 5.01343646373176,
  'RMSE': 2.2390704463530753,
  'R2': 0.5259285835364947}}

In [237]:
db1 = pd.DataFrame(ds1)
db2 = pd.DataFrame(ds2)
db3 = pd.DataFrame(ds3)
db4 = pd.DataFrame(ds4)

In [238]:
data4 = [db1, db2,db3,db4]
df4 = pd.concat(data4, ignore_index=False, sort=False)

In [239]:
df4

,method,percent,start_lat,start_lon,end_lat,end_lon,usertype,hour,temp,feelslike,...,sealevelpressure,visibility,solarradiation,conditions,dist,birthyear,holiday,day,month,gender
MAE,drop,20%,1.570763,1.570763,1.570763,1.570763,1.570763,1.570763,1.570763,1.570763,...,1.570763,1.570763,1.570763,1.570763,1.570763,1.570763,1.570763,1.570763,1.570763,1.570763
MSE,drop,20%,4.985157,4.985157,4.985157,4.985157,4.985157,4.985157,4.985157,4.985157,...,4.985157,4.985157,4.985157,4.985157,4.985157,4.985157,4.985157,4.985157,4.985157,4.985157
RMSE,drop,20%,2.232747,2.232747,2.232747,2.232747,2.232747,2.232747,2.232747,2.232747,...,2.232747,2.232747,2.232747,2.232747,2.232747,2.232747,2.232747,2.232747,2.232747,2.232747
R2,drop,20%,0.528264,0.528264,0.528264,0.528264,0.528264,0.528264,0.528264,0.528264,...,0.528264,0.528264,0.528264,0.528264,0.528264,0.528264,0.528264,0.528264,0.528264,0.528264
MAE,mode,20%,1.572213,1.573120,1.572255,1.573301,1.578024,1.573727,1.572602,1.572443,...,1.572295,1.572303,1.572264,1.572314,1.762443,1.572961,1.572404,1.573192,1.572452,1.574075
MSE,mode,20%,5.000209,5.004432,5.000424,5.001870,5.032746,5.007616,5.000988,5.000257,...,4.999576,4.999549,5.001483,4.999660,6.041493,5.002701,5.001064,5.006786,5.000211,5.008700
RMSE,mode,20%,2.236115,2.237059,2.236163,2.236486,2.243378,2.237770,2.236289,2.236126,...,2.235973,2.235967,2.236400,2.235992,2.457945,2.236672,2.236306,2.237585,2.236115,2.238012
R2,mode,20%,0.527179,0.526780,0.527159,0.527022,0.524103,0.526479,0.527106,0.527175,...,0.527239,0.527242,0.527059,0.527231,0.428715,0.526944,0.527099,0.526557,0.527179,0.526376
MAE,mean,20%,1.572255,1.573041,1.572284,1.573303,NaN,1.573218,1.572595,1.572452,...,1.572286,1.572288,1.572193,NaN,1.753386,1.572814,NaN,NaN,NaN,NaN
MSE,mean,20%,5.000223,5.004208,5.000371,5.001814,NaN,5.003379,5.000957,5.000300,...,4.999565,4.999533,5.000728,NaN,6.006749,5.001803,NaN,NaN,NaN,NaN
RMSE,mean,20%,2.236118,2.237009,2.236151,2.236474,NaN,2.236824,2.236282,2.236135,...,2.235971,2.235964,2.236231,NaN,2.450867,2.236471,NaN,NaN,NaN,NaN
R2,mean,20%,0.527178,0.526801,0.527164,0.527028,NaN,0.526880,0.527109,0.527171,...,0.527240,0.527243,0.527130,NaN,0.432001,0.527029,NaN,NaN,NaN,NaN
MAE,sample,20%,1.572186,1.573524,1.572241,1.573737,1.582656,1.574408,1.572626,1.572445,...,1.572262,1.572277,1.572292,1.572321,1.885754,1.573291,1.572368,1.573793,1.572623,1.574655
MSE,sample,20%,5.000124,5.006690,5.001055,5.003684,5.055900,5.009883,5.001133,5.000303,...,4.999459,4.999350,5.001870,4.999889,6.783894,5.003967,5.000253,5.010243,5.000604,5.013436
RMSE,sample,20%,2.236096,2.237563,2.236304,2.236892,2.248533,2.238277,2.236321,2.236136,...,2.235947,2.235923,2.236486,2.236043,2.604591,2.236955,2.236125,2.238357,2.236203,2.239070
R2,sample,20%,0.527187,0.526567,0.527099,0.526851,0.521913,0.526265,0.527092,0.527171,...,0.527250,0.527261,0.527022,0.527210,0.358514,0.526824,0.527175,0.526231,0.527142,0.525929

In [240]:
dq1= {'method': 'drop','percent': '30%','start_lat': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'start_lon': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'end_lat': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'end_lon': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'usertype': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'hour': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'temp': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'feelslike': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'dew': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'snowdepth': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'winddir': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'sealevelpressure': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'visibility': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'solarradiation': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'conditions': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'dist': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'birthyear': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'holiday': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'day': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'month': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368},
 'gender': {'MAE': 1.570092051728064,
  'MSE': 4.998546337663303,
  'RMSE': 2.2357429050906776,
  'R2': 0.5276049772015368}}

In [241]:
dq2= {'method': 'mode','percent': '30%','start_lat': {'MAE': 1.5721465611020429,
  'MSE': 4.999929511049258,
  'RMSE': 2.2360522156356852,
  'R2': 0.5272058033111189},
 'start_lon': {'MAE': 1.5734303277634747,
  'MSE': 5.006166054473103,
  'RMSE': 2.2374463243781073,
  'R2': 0.52661607468961},
 'end_lat': {'MAE': 1.5722425217616058,
  'MSE': 5.000655589703993,
  'RMSE': 2.236214567009166,
  'R2': 0.5271371451883312},
 'end_lon': {'MAE': 1.5736280477895215,
  'MSE': 5.003302315729974,
  'RMSE': 2.2368062758607357,
  'R2': 0.5268868703189469},
 'usertype': {'MAE': 1.5803608587891416,
  'MSE': 5.045779589961381,
  'RMSE': 2.2462812802410523,
  'R2': 0.5228702119433858},
 'hour': {'MAE': 1.5742716901763405,
  'MSE': 5.010193500926595,
  'RMSE': 2.238346153061808,
  'R2': 0.5262352386585263},
 'temp': {'MAE': 1.5725853678849735,
  'MSE': 5.000986852309775,
  'RMSE': 2.236288633497424,
  'R2': 0.5271058209392099},
 'feelslike': {'MAE': 1.5724489568661166,
  'MSE': 5.000268340459024,
  'RMSE': 2.2361279794455022,
  'R2': 0.5271737635437079},
 'dew': {'MAE': 1.572215024542427,
  'MSE': 4.999592958791809,
  'RMSE': 2.2359769584662113,
  'R2': 0.5272376277506139},
 'snowdepth': {'MAE': 1.5724779614154694,
  'MSE': 4.9996821147874755,
  'RMSE': 2.2359968950755444,
  'R2': 0.5272291971442908},
 'winddir': {'MAE': 1.5723133981032065,
  'MSE': 4.999634316109916,
  'RMSE': 2.235986206600997,
  'R2': 0.5272337169954826},
 'sealevelpressure': {'MAE': 1.5723070873546379,
  'MSE': 4.999761741688029,
  'RMSE': 2.2360147006869227,
  'R2': 0.5272216676108447},
 'visibility': {'MAE': 1.5723006829505943,
  'MSE': 4.999506454310827,
  'RMSE': 2.2359576146051667,
  'R2': 0.5272458076292512},
 'solarradiation': {'MAE': 1.572507492791158,
  'MSE': 5.00247878928954,
  'RMSE': 2.2366221829557045,
  'R2': 0.5269647431211526},
 'conditions': {'MAE': 1.5723254160232636,
  'MSE': 4.999724460633274,
  'RMSE': 2.2360063641754855,
  'R2': 0.5272251929138105},
 'dist': {'MAE': 1.8561350470967874,
  'MSE': 6.549322575974403,
  'RMSE': 2.559164429257019,
  'R2': 0.38069492793422166},
 'birthyear': {'MAE': 1.573467335793671,
  'MSE': 5.004806268360204,
  'RMSE': 2.237142433632737,
  'R2': 0.5267446562989099},
 'holiday': {'MAE': 1.5723632037665802,
  'MSE': 5.000446810984255,
  'RMSE': 2.2361678852412346,
  'R2': 0.5271568873400688},
 'day': {'MAE': 1.5739036144582799,
  'MSE': 5.011955060431806,
  'RMSE': 2.2387396142543703,
  'R2': 0.5260686652879728},
 'month': {'MAE': 1.5725325600424471,
  'MSE': 5.00087636019582,
  'RMSE': 2.2362639290110233,
  'R2': 0.5271162690925573},
 'gender': {'MAE': 1.5753027908940263,
  'MSE': 5.013753211316957,
  'RMSE': 2.2391411771741767,
  'R2': 0.5258986318302227}}

In [242]:
dq3= {'method': 'mean','percent': '30%','start_lat': {'MAE': 1.5721572333471134,
  'MSE': 4.999910705242945,
  'RMSE': 2.236048010495961,
  'R2': 0.5272075815914063},
 'start_lon': {'MAE': 1.5734004694548605,
  'MSE': 5.005932280703891,
  'RMSE': 2.237394082566567,
  'R2': 0.5266381803775357},
 'end_lat': {'MAE': 1.5722264403256243,
  'MSE': 5.000585645077464,
  'RMSE': 2.2361989278857695,
  'R2': 0.5271437591642762},
 'end_lon': {'MAE': 1.5735868254201535,
  'MSE': 5.003234376150777,
  'RMSE': 2.236791089071748,
  'R2': 0.5268932946972704},
 'hour': {'MAE': 1.5734525860539819,
  'MSE': 5.005085899249781,
  'RMSE': 2.237204930096879,
  'R2': 0.5267182143537756},
 'temp': {'MAE': 1.572568062442452,
  'MSE': 5.000875869431442,
  'RMSE': 2.2362638192823856,
  'R2': 0.5271163154993215},
 'feelslike': {'MAE': 1.572444293322377,
  'MSE': 5.000260285147723,
  'RMSE': 2.236126178270744,
  'R2': 0.5271745252553335},
 'dew': {'MAE': 1.572221528570146,
  'MSE': 4.999426450259082,
  'RMSE': 2.235939724200785,
  'R2': 0.5272533728261792},
 'snowdepth': {'MAE': 1.5724611103813018,
  'MSE': 4.999688008060013,
  'RMSE': 2.2359982128928486,
  'R2': 0.5272286398754236},
 'winddir': {'MAE': 1.5723136524283967,
  'MSE': 4.999629282255543,
  'RMSE': 2.2359850809554933,
  'R2': 0.5272341929976201},
 'visibility': {'MAE': 1.5722924691764768,
  'MSE': 4.999501603747934,
  'RMSE': 2.235956529932533,
  'R2': 0.5272462662993149},
 'sealevelpressure': {'MAE': 1.5723074604979541,
  'MSE': 4.999759149752066,
  'RMSE': 2.236014121098538,
  'R2': 0.5272219127047562},
 'solarradiation': {'MAE': 1.5723404945598696,
  'MSE': 5.001674346789157,
  'RMSE': 2.2364423414855024,
  'R2': 0.5270408113426968},
 'dist': {'MAE': 1.8436018167527466,
  'MSE': 6.505155260203173,
  'RMSE': 2.550520586116327,
  'R2': 0.3848713969291978},
 'birthyear': {'MAE': 1.5731764582847292,
  'MSE': 5.003820468537657,
  'RMSE': 2.2369220971096997,
  'R2': 0.5268378737001087}}

In [243]:
dq4= {'method': 'sample','percent': '30%','start_lat': {'MAE': 1.5720886041598578,
  'MSE': 5.000219850269955,
  'RMSE': 2.2361171369742587,
  'R2': 0.5271783487843473},
 'start_lon': {'MAE': 1.5739702088576695,
  'MSE': 5.008577217842738,
  'RMSE': 2.2379850798972583,
  'R2': 0.5263880746656271},
 'end_lat': {'MAE': 1.5722364593283198,
  'MSE': 5.001017563407101,
  'RMSE': 2.2362955000194185,
  'R2': 0.5271029168925514},
 'end_lon': {'MAE': 1.5741259999037256,
  'MSE': 5.005285108686993,
  'RMSE': 2.237249451600557,
  'R2': 0.5266993770750436},
 'usertype': {'MAE': 1.5868533509084646,
  'MSE': 5.081024215652425,
  'RMSE': 2.25411273357222,
  'R2': 0.5195374740609069},
 'hour': {'MAE': 1.5743533339872748,
  'MSE': 5.009625737279954,
  'RMSE': 2.2382193228725273,
  'R2': 0.5262889264868507},
 'temp': {'MAE': 1.5726299041934277,
  'MSE': 5.001040252337177,
  'RMSE': 2.2363005728964915,
  'R2': 0.5271007714234112},
 'feelslike': {'MAE': 1.5724451190754378,
  'MSE': 5.000230666638357,
  'RMSE': 2.2361195555332807,
  'R2': 0.5271773259866861},
 'dew': {'MAE': 1.572277617385327,
  'MSE': 4.9996820699027635,
  'RMSE': 2.235996885038699,
  'R2': 0.5272292013885969},
 'snowdepth': {'MAE': 1.5724620960476259,
  'MSE': 4.99953171311516,
  'RMSE': 2.2359632629171617,
  'R2': 0.5272434191523583},
 'winddir': {'MAE': 1.5723246096757268,
  'MSE': 4.999629360502241,
  'RMSE': 2.2359850984526353,
  'R2': 0.5272341855985989},
 'sealevelpressure': {'MAE': 1.5722820598307068,
  'MSE': 4.999737614583705,
  'RMSE': 2.236009305567333,
  'R2': 0.5272239490739896},
 'visibility': {'MAE': 1.5722769337963942,
  'MSE': 4.999426426082414,
  'RMSE': 2.2359397187944077,
  'R2': 0.5272533751123292},
 'solarradiation': {'MAE': 1.5727603036636733,
  'MSE': 5.003297883323046,
  'RMSE': 2.2368052850713327,
  'R2': 0.5268872894481103},
 'conditions': {'MAE': 1.5724645073920676,
  'MSE': 5.000089740318113,
  'RMSE': 2.236088043954914,
  'R2': 0.527190652003828},
 'dist': {'MAE': 2.0239016317270973,
  'MSE': 7.523996090163529,
  'RMSE': 2.74299035546309,
  'R2': 0.2885296323722305},
 'birthyear': {'MAE': 1.5734152327732556,
  'MSE': 5.005434157742105,
  'RMSE': 2.2372827621340368,
  'R2': 0.5266852829706922},
 'holiday': {'MAE': 1.572371279164073,
  'MSE': 5.000729183124015,
  'RMSE': 2.236231021858881,
  'R2': 0.5271301861818445},
 'day': {'MAE': 1.5743465396938983,
  'MSE': 5.0163716572102235,
  'RMSE': 2.2397257995590047,
  'R2': 0.525651031135064},
 'month': {'MAE': 1.572608656263285,
  'MSE': 5.000909019742142,
  'RMSE': 2.2362712312557576,
  'R2': 0.5271131808002256},
 'gender': {'MAE': 1.5763050431118,
  'MSE': 5.019699193127871,
  'RMSE': 2.240468520896438,
  'R2': 0.5253363787649334}}

In [244]:
dc1 = pd.DataFrame(dq1)
dc2 = pd.DataFrame(dq2)
dc3 = pd.DataFrame(dq3)
dc4 = pd.DataFrame(dq4)

In [245]:
data5 = [dc1, dc2,dc3,dc4]
df5 = pd.concat(data5, ignore_index=False, sort=False)

In [246]:
df5

,method,percent,start_lat,start_lon,end_lat,end_lon,usertype,hour,temp,feelslike,...,sealevelpressure,visibility,solarradiation,conditions,dist,birthyear,holiday,day,month,gender
MAE,drop,30%,1.570092,1.570092,1.570092,1.570092,1.570092,1.570092,1.570092,1.570092,...,1.570092,1.570092,1.570092,1.570092,1.570092,1.570092,1.570092,1.570092,1.570092,1.570092
MSE,drop,30%,4.998546,4.998546,4.998546,4.998546,4.998546,4.998546,4.998546,4.998546,...,4.998546,4.998546,4.998546,4.998546,4.998546,4.998546,4.998546,4.998546,4.998546,4.998546
RMSE,drop,30%,2.235743,2.235743,2.235743,2.235743,2.235743,2.235743,2.235743,2.235743,...,2.235743,2.235743,2.235743,2.235743,2.235743,2.235743,2.235743,2.235743,2.235743,2.235743
R2,drop,30%,0.527605,0.527605,0.527605,0.527605,0.527605,0.527605,0.527605,0.527605,...,0.527605,0.527605,0.527605,0.527605,0.527605,0.527605,0.527605,0.527605,0.527605,0.527605
MAE,mode,30%,1.572147,1.573430,1.572243,1.573628,1.580361,1.574272,1.572585,1.572449,...,1.572307,1.572301,1.572507,1.572325,1.856135,1.573467,1.572363,1.573904,1.572533,1.575303
MSE,mode,30%,4.999930,5.006166,5.000656,5.003302,5.045780,5.010194,5.000987,5.000268,...,4.999762,4.999506,5.002479,4.999724,6.549323,5.004806,5.000447,5.011955,5.000876,5.013753
RMSE,mode,30%,2.236052,2.237446,2.236215,2.236806,2.246281,2.238346,2.236289,2.236128,...,2.236015,2.235958,2.236622,2.236006,2.559164,2.237142,2.236168,2.238740,2.236264,2.239141
R2,mode,30%,0.527206,0.526616,0.527137,0.526887,0.522870,0.526235,0.527106,0.527174,...,0.527222,0.527246,0.526965,0.527225,0.380695,0.526745,0.527157,0.526069,0.527116,0.525899
MAE,mean,30%,1.572157,1.573400,1.572226,1.573587,NaN,1.573453,1.572568,1.572444,...,1.572307,1.572292,1.572340,NaN,1.843602,1.573176,NaN,NaN,NaN,NaN
MSE,mean,30%,4.999911,5.005932,5.000586,5.003234,NaN,5.005086,5.000876,5.000260,...,4.999759,4.999502,5.001674,NaN,6.505155,5.003820,NaN,NaN,NaN,NaN
RMSE,mean,30%,2.236048,2.237394,2.236199,2.236791,NaN,2.237205,2.236264,2.236126,...,2.236014,2.235957,2.236442,NaN,2.550521,2.236922,NaN,NaN,NaN,NaN
R2,mean,30%,0.527208,0.526638,0.527144,0.526893,NaN,0.526718,0.527116,0.527175,...,0.527222,0.527246,0.527041,NaN,0.384871,0.526838,NaN,NaN,NaN,NaN
MAE,sample,30%,1.572089,1.573970,1.572236,1.574126,1.586853,1.574353,1.572630,1.572445,...,1.572282,1.572277,1.572760,1.572465,2.023902,1.573415,1.572371,1.574347,1.572609,1.576305
MSE,sample,30%,5.000220,5.008577,5.001018,5.005285,5.081024,5.009626,5.001040,5.000231,...,4.999738,4.999426,5.003298,5.000090,7.523996,5.005434,5.000729,5.016372,5.000909,5.019699
RMSE,sample,30%,2.236117,2.237985,2.236296,2.237249,2.254113,2.238219,2.236301,2.236120,...,2.236009,2.235940,2.236805,2.236088,2.742990,2.237283,2.236231,2.239726,2.236271,2.240469
R2,sample,30%,0.527178,0.526388,0.527103,0.526699,0.519537,0.526289,0.527101,0.527177,...,0.527224,0.527253,0.526887,0.527191,0.288530,0.526685,0.527130,0.525651,0.527113,0.525336

In [247]:
de1= {'method': 'drop','percent': '40%','start_lat': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'start_lon': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'end_lat': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'end_lon': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'usertype': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'hour': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'temp': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'feelslike': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'dew': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'snowdepth': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'winddir': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'sealevelpressure': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'visibility': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'solarradiation': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'conditions': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'dist': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'birthyear': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'holiday': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'day': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'month': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493},
 'gender': {'MAE': 1.5718435430420257,
  'MSE': 4.989252368774693,
  'RMSE': 2.23366344124953,
  'R2': 0.5285979071652493}}

In [248]:
de2= {'method': 'mode','percent': '40%','start_lat': {'MAE': 1.5721555184883094,
  'MSE': 5.000266818358792,
  'RMSE': 2.23612763910265,
  'R2': 0.5271739074737682},
 'start_lon': {'MAE': 1.573616678407497,
  'MSE': 5.007385739067627,
  'RMSE': 2.2377188695337997,
  'R2': 0.526500741104045},
 'end_lat': {'MAE': 1.5722592342381496,
  'MSE': 5.000713592440277,
  'RMSE': 2.2362275359274775,
  'R2': 0.527131660439587},
 'end_lon': {'MAE': 1.5738191643862862,
  'MSE': 5.004428276422789,
  'RMSE': 2.2370579510649224,
  'R2': 0.526780399281688},
 'usertype': {'MAE': 1.584233998072505,
  'MSE': 5.068906250143438,
  'RMSE': 2.2514231610568984,
  'R2': 0.5206833509689042},
 'hour': {'MAE': 1.5749051899787996,
  'MSE': 5.014413172077741,
  'RMSE': 2.2392885414965487,
  'R2': 0.5258362258268877},
 'temp': {'MAE': 1.5725735644807857,
  'MSE': 5.001005303982387,
  'RMSE': 2.2362927590059374,
  'R2': 0.5271040761458661},
 'feelslike': {'MAE': 1.5724330600167897,
  'MSE': 5.000231855200692,
  'RMSE': 2.2361198212977524,
  'R2': 0.5271772135960269},
 'dew': {'MAE': 1.5721996221202323,
  'MSE': 4.999570068364107,
  'RMSE': 2.23597183979676,
  'R2': 0.5272397922734045},
 'snowdepth': {'MAE': 1.5724061079694631,
  'MSE': 4.99956198341987,
  'RMSE': 2.235970031869808,
  'R2': 0.5272405567871254},
 'winddir': {'MAE': 1.5723238810951754,
  'MSE': 4.999666464148177,
  'RMSE': 2.2359933953722173,
  'R2': 0.5272306770714414},
 'sealevelpressure': {'MAE': 1.5723022155767554,
  'MSE': 4.999732616039039,
  'RMSE': 2.236008187829159,
  'R2': 0.5272244217372352},
 'visibility': {'MAE': 1.57227588027424,
  'MSE': 4.999380858457678,
  'RMSE': 2.235929528956062,
  'R2': 0.5272576839947812},
 'solarradiation': {'MAE': 1.5724206433286065,
  'MSE': 5.003211557353489,
  'RMSE': 2.2367859882772625,
  'R2': 0.5268954524466765},
 'conditions': {'MAE': 1.5722978085207981,
  'MSE': 4.999827696767029,
  'RMSE': 2.236029448993691,
  'R2': 0.5272154308872019},
 'dist': {'MAE': 1.9455523809415947,
  'MSE': 7.015479441198898,
  'RMSE': 2.6486750350314585,
  'R2': 0.33661505438045014},
 'birthyear': {'MAE': 1.5740158293626927,
  'MSE': 5.00719222831917,
  'RMSE': 2.237675630720228,
  'R2': 0.5265190395137855},
 'holiday': {'MAE': 1.5723795926809652,
  'MSE': 5.000445359029938,
  'RMSE': 2.236167560588861,
  'R2': 0.5271570246371193},
 'day': {'MAE': 1.5744434303195334,
  'MSE': 5.015736397854534,
  'RMSE': 2.2395839787457255,
  'R2': 0.525711101369274},
 'month': {'MAE': 1.57257741811018,
  'MSE': 5.001174596709993,
  'RMSE': 2.2363306098853077,
  'R2': 0.527088067796353},
 'gender': {'MAE': 1.57616392387623,
  'MSE': 5.018245543025463,
  'RMSE': 2.2401440897909812,
  'R2': 0.5254738361692659}}

In [249]:
de3= {'method': 'mean','percent': '40%','start_lat': {'MAE': 1.5721471578792463,
  'MSE': 5.000139174111262,
  'RMSE': 2.236099097560585,
  'R2': 0.5271859775358241},
 'start_lon': {'MAE': 1.5736120365835713,
  'MSE': 5.007394272816231,
  'RMSE': 2.237720776329395,
  'R2': 0.5264999341513056},
 'end_lat': {'MAE': 1.5722384607635904,
  'MSE': 5.0004343416614585,
  'RMSE': 2.2361650971387284,
  'R2': 0.5271580664413825},
 'end_lon': {'MAE': 1.573764050718548,
  'MSE': 5.004177943378721,
  'RMSE': 2.2370019989661882,
  'R2': 0.5268040708174992},
 'hour': {'MAE': 1.5740042857372634,
  'MSE': 5.008694647906655,
  'RMSE': 2.2380113154107724,
  'R2': 0.526376970458535},
 'temp': {'MAE': 1.5725606180638567,
  'MSE': 5.000980572160991,
  'RMSE': 2.2362872293515856,
  'R2': 0.5271064147911617},
 'feelslike': {'MAE': 1.5724268288254577,
  'MSE': 5.000227668407885,
  'RMSE': 2.2361188851239295,
  'R2': 0.5271776094998766},
 'dew': {'MAE': 1.5722344803550314,
  'MSE': 4.999604181491268,
  'RMSE': 2.235979468038843,
  'R2': 0.5272365665302181},
 'snowdepth': {'MAE': 1.5723783512621081,
  'MSE': 4.999504979985795,
  'RMSE': 2.2359572849197713,
  'R2': 0.5272459470416806},
 'winddir': {'MAE': 1.5723248625731172,
  'MSE': 4.999665508185191,
  'RMSE': 2.235993181605255,
  'R2': 0.5272307674674663},
 'visibility': {'MAE': 1.5722672989492972,
  'MSE': 4.999406215000372,
  'RMSE': 2.2359351991952656,
  'R2': 0.527255286275732},
 'sealevelpressure': {'MAE': 1.572304826936333,
  'MSE': 4.999752110221473,
  'RMSE': 2.2360125469731766,
  'R2': 0.5272225783639828},
 'solarradiation': {'MAE': 1.5720645195018987,
  'MSE': 5.0019381793995,
  'RMSE': 2.236501325597528,
  'R2': 0.5270158632855708},
 'dist': {'MAE': 1.9307534561491226,
  'MSE': 6.964783085631554,
  'RMSE': 2.6390875479285554,
  'R2': 0.3414089105043311},
 'birthyear': {'MAE': 1.5736614577532415,
  'MSE': 5.005858582132426,
  'RMSE': 2.2373776127717973,
  'R2': 0.5266451493271611}}

In [250]:
de4= {'method': 'sample','percent': '40%','start_lat': {'MAE': 1.5720913518611388,
  'MSE': 5.000163820032112,
  'RMSE': 2.2361046084725356,
  'R2': 0.5271836470132989},
 'start_lon': {'MAE': 1.5738936507082024,
  'MSE': 5.008726592925765,
  'RMSE': 2.2380184523202136,
  'R2': 0.5263739497320197},
 'end_lat': {'MAE': 1.5721622707824663,
  'MSE': 5.001062165281423,
  'RMSE': 2.2363054722647853,
  'R2': 0.5270986993316248},
 'end_lon': {'MAE': 1.5742167112695697,
  'MSE': 5.006080348072839,
  'RMSE': 2.23742717156846,
  'R2': 0.5266241791015971},
 'usertype': {'MAE': 1.5903511119131941,
  'MSE': 5.100343832021567,
  'RMSE': 2.2583940825333313,
  'R2': 0.5177106078058127},
 'hour': {'MAE': 1.5750620753973457,
  'MSE': 5.015437742448758,
  'RMSE': 2.239517301216661,
  'R2': 0.5257393422759404},
 'temp': {'MAE': 1.572590351524022,
  'MSE': 5.001011644715819,
  'RMSE': 2.2362941766940723,
  'R2': 0.5271034765650195},
 'feelslike': {'MAE': 1.5724303507581607,
  'MSE': 5.000219551996955,
  'RMSE': 2.2361170702798536,
  'R2': 0.5271783769890936},
 'dew': {'MAE': 1.5722251958796072,
  'MSE': 4.999562075837866,
  'RMSE': 2.2359700525360053,
  'R2': 0.527240548048064},
 'snowdepth': {'MAE': 1.5725691075102128,
  'MSE': 4.999654647337131,
  'RMSE': 2.235990752963243,
  'R2': 0.5272317944711316},
 'winddir': {'MAE': 1.572349365347802,
  'MSE': 4.999787935057879,
  'RMSE': 2.236020557834359,
  'R2': 0.5272191907612752},
 'sealevelpressure': {'MAE': 1.5723423253135038,
  'MSE': 4.999873373738109,
  'RMSE': 2.236039662827587,
  'R2': 0.5272111116649407},
 'visibility': {'MAE': 1.572290842461933,
  'MSE': 4.999466337312114,
  'RMSE': 2.2359486437107883,
  'R2': 0.5272496010995669},
 'solarradiation': {'MAE': 1.5724091444657962,
  'MSE': 5.00353235930668,
  'RMSE': 2.2368576975987273,
  'R2': 0.5268651173586677},
 'conditions': {'MAE': 1.5723189979477965,
  'MSE': 4.999808900401097,
  'RMSE': 2.236025245922124,
  'R2': 0.5272172082748054},
 'dist': {'MAE': 2.135700172712282,
  'MSE': 8.094257162739659,
  'RMSE': 2.845040801594884,
  'R2': 0.23460564702088704},
 'birthyear': {'MAE': 1.5738731719068262,
  'MSE': 5.007786752224055,
  'RMSE': 2.237808470853584,
  'R2': 0.5264628212308275},
 'holiday': {'MAE': 1.5723257268749433,
  'MSE': 5.000371349118724,
  'RMSE': 2.236151012145361,
  'R2': 0.5271640230270852},
 'day': {'MAE': 1.5749253152821625,
  'MSE': 5.019343757967233,
  'RMSE': 2.2403891978777333,
  'R2': 0.52536998877501},
 'month': {'MAE': 1.5727283394507225,
  'MSE': 5.001678122882134,
  'RMSE': 2.236443185704062,
  'R2': 0.5270404542746937},
 'gender': {'MAE': 1.577239177013259,
  'MSE': 5.023521937373477,
  'RMSE': 2.2413214712248393,
  'R2': 0.5249748994099236}}

In [251]:
dh1 = pd.DataFrame(de1)
dh2 = pd.DataFrame(de2)
dh3 = pd.DataFrame(de3)
dh4 = pd.DataFrame(de4)

In [252]:
data6 = [dh1, dh2,dh3,dh4]
df6 = pd.concat(data6, ignore_index=False, sort=False)

In [253]:
df6

,method,percent,start_lat,start_lon,end_lat,end_lon,usertype,hour,temp,feelslike,...,sealevelpressure,visibility,solarradiation,conditions,dist,birthyear,holiday,day,month,gender
MAE,drop,40%,1.571844,1.571844,1.571844,1.571844,1.571844,1.571844,1.571844,1.571844,...,1.571844,1.571844,1.571844,1.571844,1.571844,1.571844,1.571844,1.571844,1.571844,1.571844
MSE,drop,40%,4.989252,4.989252,4.989252,4.989252,4.989252,4.989252,4.989252,4.989252,...,4.989252,4.989252,4.989252,4.989252,4.989252,4.989252,4.989252,4.989252,4.989252,4.989252
RMSE,drop,40%,2.233663,2.233663,2.233663,2.233663,2.233663,2.233663,2.233663,2.233663,...,2.233663,2.233663,2.233663,2.233663,2.233663,2.233663,2.233663,2.233663,2.233663,2.233663
R2,drop,40%,0.528598,0.528598,0.528598,0.528598,0.528598,0.528598,0.528598,0.528598,...,0.528598,0.528598,0.528598,0.528598,0.528598,0.528598,0.528598,0.528598,0.528598,0.528598
MAE,mode,40%,1.572156,1.573617,1.572259,1.573819,1.584234,1.574905,1.572574,1.572433,...,1.572302,1.572276,1.572421,1.572298,1.945552,1.574016,1.572380,1.574443,1.572577,1.576164
MSE,mode,40%,5.000267,5.007386,5.000714,5.004428,5.068906,5.014413,5.001005,5.000232,...,4.999733,4.999381,5.003212,4.999828,7.015479,5.007192,5.000445,5.015736,5.001175,5.018246
RMSE,mode,40%,2.236128,2.237719,2.236228,2.237058,2.251423,2.239289,2.236293,2.236120,...,2.236008,2.235930,2.236786,2.236029,2.648675,2.237676,2.236168,2.239584,2.236331,2.240144
R2,mode,40%,0.527174,0.526501,0.527132,0.526780,0.520683,0.525836,0.527104,0.527177,...,0.527224,0.527258,0.526895,0.527215,0.336615,0.526519,0.527157,0.525711,0.527088,0.525474
MAE,mean,40%,1.572147,1.573612,1.572238,1.573764,NaN,1.574004,1.572561,1.572427,...,1.572305,1.572267,1.572065,NaN,1.930753,1.573661,NaN,NaN,NaN,NaN
MSE,mean,40%,5.000139,5.007394,5.000434,5.004178,NaN,5.008695,5.000981,5.000228,...,4.999752,4.999406,5.001938,NaN,6.964783,5.005859,NaN,NaN,NaN,NaN
RMSE,mean,40%,2.236099,2.237721,2.236165,2.237002,NaN,2.238011,2.236287,2.236119,...,2.236013,2.235935,2.236501,NaN,2.639088,2.237378,NaN,NaN,NaN,NaN
R2,mean,40%,0.527186,0.526500,0.527158,0.526804,NaN,0.526377,0.527106,0.527178,...,0.527223,0.527255,0.527016,NaN,0.341409,0.526645,NaN,NaN,NaN,NaN
MAE,sample,40%,1.572091,1.573894,1.572162,1.574217,1.590351,1.575062,1.572590,1.572430,...,1.572342,1.572291,1.572409,1.572319,2.135700,1.573873,1.572326,1.574925,1.572728,1.577239
MSE,sample,40%,5.000164,5.008727,5.001062,5.006080,5.100344,5.015438,5.001012,5.000220,...,4.999873,4.999466,5.003532,4.999809,8.094257,5.007787,5.000371,5.019344,5.001678,5.023522
RMSE,sample,40%,2.236105,2.238018,2.236305,2.237427,2.258394,2.239517,2.236294,2.236117,...,2.236040,2.235949,2.236858,2.236025,2.845041,2.237808,2.236151,2.240389,2.236443,2.241321
R2,sample,40%,0.527184,0.526374,0.527099,0.526624,0.517711,0.525739,0.527103,0.527178,...,0.527211,0.527250,0.526865,0.527217,0.234606,0.526463,0.527164,0.525370,0.527040,0.524975

In [254]:
data7 = [df1, df2,df3,df4,df5,df6]
df = pd.concat(data7, ignore_index=False, sort=False)

In [255]:
df

,method,percent,start_lat,start_lon,end_lat,end_lon,usertype,hour,temp,feelslike,...,sealevelpressure,visibility,solarradiation,conditions,dist,birthyear,holiday,day,month,gender
MAE,drop,1%,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,...,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023
MSE,drop,1%,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,...,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234
RMSE,drop,1%,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,...,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015
R2,drop,1%,0.526629,0.526629,0.526629,0.526629,0.526629,0.526629,0.526629,0.526629,...,0.526629,0.526629,0.526629,0.526629,0.526629,0.526629,0.526629,0.526629,0.526629,0.526629
MAE,mode,1%,1.572305,1.572348,1.572317,1.572330,1.572420,1.572419,1.572422,1.572435,...,1.572316,1.572314,1.572250,1.572326,1.582974,1.572384,1.572313,1.572460,1.572353,1.572428
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
R2,mean,40%,0.527186,0.526500,0.527158,0.526804,NaN,0.526377,0.527106,0.527178,...,0.527223,0.527255,0.527016,NaN,0.341409,0.526645,NaN,NaN,NaN,NaN
MAE,sample,40%,1.572091,1.573894,1.572162,1.574217,1.590351,1.575062,1.572590,1.572430,...,1.572342,1.572291,1.572409,1.572319,2.135700,1.573873,1.572326,1.574925,1.572728,1.577239
MSE,sample,40%,5.000164,5.008727,5.001062,5.006080,5.100344,5.015438,5.001012,5.000220,...,4.999873,4.999466,5.003532,4.999809,8.094257,5.007787,5.000371,5.019344,5.001678,5.023522
RMSE,sample,40%,2.236105,2.238018,2.236305,2.237427,2.258394,2.239517,2.236294,2.236117,...,2.236040,2.235949,2.236858,2.236025,2.845041,2.237808,2.236151,2.240389,2.236443,2.241321
R2,sample,40%,0.527184,0.526374,0.527099,0.526624,0.517711,0.525739,0.527103,0.527178,...,0.527211,0.527250,0.526865,0.527217,0.234606,0.526463,0.527164,0.525370,0.527040,0.524975

In [258]:
df.to_csv("../../dataset/results/imputation_results_full.csv")

In [259]:
data1 = pd.read_csv("../../dataset/results/imputation_results_full.csv")

In [260]:
data2 = pd.read_csv("../../dataset/results/bad_imputation_results.csv")

In [261]:
cols = ['Unnamed: 0', 'method', 'percent', 'start_lat', 'start_lon', 'end_lat',
       'end_lon', 'usertype', 'hour', 'temp', 'feelslike', 'dew', 'snowdepth',
       'winddir', 'sealevelpressure', 'visibility', 'solarradiation',
       'conditions', 'dist', 'birthyear', 'holiday', 'day', 'month', 'gender']
d = [['R2', 'full','0%',0.5272377063160185,0.5272377063160185,0.5272377063160185,0.5272377063160185,0.5272377063160185,0.5272377063160185,0.5272377063160185,0.5272377063160185,0.5272377063160185,0.5272377063160185,0.5272377063160185,
      0.5272377063160185,0.5272377063160185,0.5272377063160185,0.5272377063160185,0.5272377063160185,0.5272377063160185,0.5272377063160185,0.5272377063160185,0.5272377063160185,0.5272377063160185],
    ['RMSE', 'full','0%',2.2359767726747313,2.2359767726747313,2.2359767726747313,2.2359767726747313,2.2359767726747313,2.2359767726747313,2.2359767726747313,2.2359767726747313,2.2359767726747313,2.2359767726747313,2.2359767726747313,
      2.2359767726747313,2.2359767726747313,2.2359767726747313,2.2359767726747313,2.2359767726747313,2.2359767726747313,2.2359767726747313,2.2359767726747313,2.2359767726747313,2.2359767726747313]]
data3 = pd.DataFrame(data=d, columns=cols)
data3

,Unnamed: 0,method,percent,start_lat,start_lon,end_lat,end_lon,usertype,hour,temp,...,sealevelpressure,visibility,solarradiation,conditions,dist,birthyear,holiday,day,month,gender
0,R2,full,0%,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,...,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238
1,RMSE,full,0%,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,...,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977

In [262]:
data = [data3, data1, data2]
df = pd.concat(data, ignore_index=False, sort=False)

In [263]:
df

,Unnamed: 0,method,percent,start_lat,start_lon,end_lat,end_lon,usertype,hour,temp,...,sealevelpressure,visibility,solarradiation,conditions,dist,birthyear,holiday,day,month,gender
0,R2,full,0%,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,...,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238
1,RMSE,full,0%,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,...,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977
0,MAE,drop,1%,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,...,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023
1,MSE,drop,1%,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,...,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234
2,RMSE,drop,1%,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,...,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19,R2,bad,30%,0.527139,0.526179,0.526942,0.526368,0.522956,0.525657,0.527094,...,0.527226,0.527250,0.526699,0.527227,0.096685,0.526399,0.527157,0.526167,0.527071,0.526151
20,MAE,bad,40%,1.571987,1.574234,1.572207,1.575020,1.583942,1.575421,1.572614,...,1.572292,1.572276,1.572694,1.572304,2.417370,1.574569,1.572376,1.574157,1.572621,1.575224
21,MSE,bad,40%,5.000612,5.010909,5.002658,5.008755,5.067413,5.017787,5.001097,...,4.999746,4.999344,5.005161,4.999849,9.585624,5.010134,5.000435,5.014089,5.001126,5.014595
22,RMSE,bad,40%,2.236205,2.238506,2.236662,2.238025,2.251091,2.240042,2.236313,...,2.236011,2.235921,2.237222,2.236034,3.096066,2.238333,2.236165,2.239216,2.236320,2.239329
23,R2,bad,40%,0.527141,0.526168,0.526948,0.526371,0.520825,0.525517,0.527095,...,0.527223,0.527261,0.526711,0.527213,0.093582,0.526241,0.527158,0.525867,0.527093,0.525819

### Rename columns

In [264]:
df = df.rename(columns={"Unnamed: 0": "estimates"})
df

,estimates,method,percent,start_lat,start_lon,end_lat,end_lon,usertype,hour,temp,...,sealevelpressure,visibility,solarradiation,conditions,dist,birthyear,holiday,day,month,gender
0,R2,full,0%,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,...,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238
1,RMSE,full,0%,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,...,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977
0,MAE,drop,1%,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,...,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023,1.573023
1,MSE,drop,1%,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,...,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234,5.004234
2,RMSE,drop,1%,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,...,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015,2.237015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19,R2,bad,30%,0.527139,0.526179,0.526942,0.526368,0.522956,0.525657,0.527094,...,0.527226,0.527250,0.526699,0.527227,0.096685,0.526399,0.527157,0.526167,0.527071,0.526151
20,MAE,bad,40%,1.571987,1.574234,1.572207,1.575020,1.583942,1.575421,1.572614,...,1.572292,1.572276,1.572694,1.572304,2.417370,1.574569,1.572376,1.574157,1.572621,1.575224
21,MSE,bad,40%,5.000612,5.010909,5.002658,5.008755,5.067413,5.017787,5.001097,...,4.999746,4.999344,5.005161,4.999849,9.585624,5.010134,5.000435,5.014089,5.001126,5.014595
22,RMSE,bad,40%,2.236205,2.238506,2.236662,2.238025,2.251091,2.240042,2.236313,...,2.236011,2.235921,2.237222,2.236034,3.096066,2.238333,2.236165,2.239216,2.236320,2.239329
23,R2,bad,40%,0.527141,0.526168,0.526948,0.526371,0.520825,0.525517,0.527095,...,0.527223,0.527261,0.526711,0.527213,0.093582,0.526241,0.527158,0.525867,0.527093,0.525819

In [265]:
df.columns

Index(['estimates', 'method', 'percent', 'start_lat', 'start_lon', 'end_lat',
       'end_lon', 'usertype', 'hour', 'temp', 'feelslike', 'dew', 'snowdepth',
       'winddir', 'sealevelpressure', 'visibility', 'solarradiation',
       'conditions', 'dist', 'birthyear', 'holiday', 'day', 'month', 'gender'],
      dtype='object')

## Visualization

In [266]:
from matplotlib.backends.backend_pdf import PdfPages

In [267]:
columns = [ 'start_lat',
       'start_lon', 'end_lat', 'end_lon',
       'usertype', 'hour', 'temp', 'feelslike', 'dew', 'snowdepth', 'winddir',
       'sealevelpressure', 'solarradiation', 'conditions', 'dist', 'birthyear',
       'holiday', 'day', 'month', 'gender']
with PdfPages('Univariate_estimates_plots.pdf') as pdf:
    for col in columns:
        sns.set_style("whitegrid")
        sns.set_palette(sns.color_palette("nipy_spectral_r"))
        sns.set_context("notebook", 
                        font_scale=1.3, 
                        rc={"lines.linewidth": 1.0})
        plt.figure(figsize=(12,3))
        plt.subplot(1,2,1)
        rmse = sns.pointplot(hue='method',
                    y=col,
                    x='percent', data=df[df['estimates'] == 'R2'], 
                      markers=['o','s','v','p','x','o'],  linestyles=["-", "--",':',"-.",'-','--'])
#         _, ylabels = plt.yticks()
#         rmse.set_yticklabels(ylabels, size=10)
        _, xlabels = plt.xticks()
        rmse.set_xticklabels(xlabels, size=10)
        plt.title(f"R2 plot of {col}", fontsize=12)
        plt.xlabel('Percent Missing', fontsize=10)
        plt.ylabel("R2 score", fontsize=10)
        # add labels here
        d1 = df[df['estimates'] == 'R2']
        d1 = d1.reset_index()
        plt.gca().get_legend().remove()
        
        ## Plot for R2
        plt.subplot(1,2,2)
        r2 = sns.pointplot(hue='method',
                    y=col,
                    x='percent', 
                    data=df[df['estimates']=='RMSE'],
                      markers=['o','s','v','p','x','o'],  linestyles=["-", "--",':',"-.", '-','--'])
#         _, ylabels = plt.yticks()
#         r2.set_yticklabels(ylabels, size=10)
        _, xlabels = plt.xticks()
        r2.set_xticklabels(xlabels, size=10)
        plt.title(f"RMSE plot of {col}", fontsize=12)
        plt.ylabel('RMSE error', fontsize=10)
        plt.xlabel('Percent Missing', fontsize=10)
        plt.gca().get_legend().remove()

        handles, labels = plt.gca().get_legend_handles_labels()

        l = plt.legend(handles, labels, bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
        plt.tight_layout()    
        pdf.savefig()  # saves the current figure into a pdf page
        plt.close()

### read boot strap interval data

In [268]:
boot_df = pd.read_csv("../../dataset/results/boot_strap_modified_results.csv")

In [270]:
boot_df.columns

Index(['estimates', 'method', 'percent', 'start_lat_HQ', 'start_lat_LQ',
       'start_lon_HQ', 'start_lon_LQ', 'end_lat_HQ', 'end_lat_LQ',
       'end_lon_HQ', 'end_lon_LQ', 'usertype_HQ', 'usertype_LQ', 'hour_HQ',
       'hour_LQ', 'temp_HQ', 'temp_LQ', 'feelslike_HQ', 'feelslike_LQ',
       'dew_HQ', 'dew_LQ', 'snowdepth_HQ', 'snowdepth_LQ', 'winddir_HQ',
       'winddir_LQ', 'sealevelpressure_HQ', 'sealevelpressure_LQ',
       'visibility_HQ', 'visibility_LQ', 'solarradiation_HQ',
       'solarradiation_LQ', 'conditions_HQ', 'conditions_LQ', 'dist_HQ',
       'dist_LQ', 'birthyear_HQ', 'birthyear_LQ', 'holiday_HQ', 'holiday_LQ',
       'day_HQ', 'day_LQ', 'month_HQ', 'month_LQ', 'gender_HQ', 'gender_LQ'],
      dtype='object')

In [271]:
boot_df['method'].unique()

array(['drop', 'mode', 'mean', 'sample', 'bad', 'full'], dtype=object)

In [272]:
boot_df

,estimates,method,percent,start_lat_HQ,start_lat_LQ,start_lon_HQ,start_lon_LQ,end_lat_HQ,end_lat_LQ,end_lon_HQ,...,birthyear_HQ,birthyear_LQ,holiday_HQ,holiday_LQ,day_HQ,day_LQ,month_HQ,month_LQ,gender_HQ,gender_LQ
0,R2,drop,1%,0.518931,0.534795,0.518931,0.534795,0.518931,0.534795,0.518931,...,0.518931,0.534795,0.518931,0.534795,0.518931,0.534795,0.518931,0.534795,0.518931,0.534795
1,RMSE,drop,1%,2.211797,2.257323,2.211797,2.257323,2.211797,2.257323,2.211797,...,2.211797,2.257323,2.211797,2.257323,2.211797,2.257323,2.211797,2.257323,2.211797,2.257323
2,intercept,drop,1%,-674.390226,-354.241091,-674.390226,-354.241091,-674.390226,-354.241091,-674.390226,...,-674.390226,-354.241091,-674.390226,-354.241091,-674.390226,-354.241091,-674.390226,-354.241091,-674.390226,-354.241091
3,R2,mode,1%,0.519730,0.535834,0.519750,0.535834,0.519748,0.535839,0.519726,...,0.519731,0.535842,0.519752,0.535840,0.519662,0.535780,0.519712,0.535816,0.519640,0.535782
4,RMSE,mode,1%,2.208209,2.255609,2.208182,2.255589,2.208197,2.255560,2.208220,...,2.208234,2.255623,2.208176,2.255563,2.208452,2.255691,2.208232,2.255618,2.208453,2.255683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,R2,bad,40%,0.519642,0.535759,0.518686,0.534920,0.519542,0.535618,0.518785,...,0.518640,0.534881,0.519667,0.535771,0.518494,0.534574,0.519595,0.535736,0.518483,0.534552
88,RMSE,bad,40%,2.208448,2.255920,2.210590,2.258331,2.208731,2.256186,2.210229,...,2.210626,2.258041,2.208378,2.255562,2.211439,2.259345,2.208530,2.256264,2.211705,2.259435
89,intercept,bad,40%,-586.736743,-306.261618,-936.960596,-652.812495,-544.565446,-255.863796,-424.401575,...,-663.048423,-381.246922,-645.804949,-364.557888,-651.043119,-363.256065,-648.851870,-367.973040,-657.402931,-375.410725
90,R2,full,0%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,RMSE,full,0%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Test

In [612]:
df_full = df[df['method'] == 'full']

In [611]:
df_bad = df[df['method'] == 'bad']

In [615]:
df_rest= df[(df['method'] != 'bad') & (df['method'] != 'full')]

In [60]:
def legend_without_duplicate_labels(figure):
    handles, labels = plt.gca().get_legend_handles_labels()
    by_label = dict(zip(labels, handles))
    figure.legend(by_label.values(), by_label.keys(),  bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)

In [640]:
columns = [ 'start_lat',
       'start_lon', 'end_lat', 'end_lon',
       'usertype', 'hour', 'temp', 'feelslike', 'dew', 'snowdepth', 'winddir',
       'sealevelpressure', 'solarradiation', 'conditions', 'dist', 'birthyear',
       'holiday', 'day', 'month', 'gender']
boot_columns = [['start_lat_HQ', 'start_lat_LQ'],
       ['start_lon_HQ', 'start_lon_LQ'], ['end_lat_HQ', 'end_lat_LQ'],
       ['end_lon_HQ', 'end_lon_LQ'], ['usertype_HQ', 'usertype_LQ'], ['hour_HQ',
       'hour_LQ'], ['temp_HQ', 'temp_LQ'], ['feelslike_HQ', 'feelslike_LQ'],
      [ 'dew_HQ', 'dew_LQ'],[ 'snowdepth_HQ', 'snowdepth_LQ'], ['winddir_HQ',
       'winddir_LQ'], ['sealevelpressure_HQ', 'sealevelpressure_LQ'],
       ['visibility_HQ', 'visibility_LQ'], ['solarradiation_HQ',
       'solarradiation_LQ'], ['conditions_HQ', 'conditions_LQ'], ['dist_HQ',
       'dist_LQ'],[ 'birthyear_HQ', 'birthyear_LQ'], ['holiday_HQ', 'holiday_LQ'],
       ['day_HQ', 'day_LQ'], ['month_HQ', 'month_LQ'], ['gender_HQ', 'gender_LQ']]
    
with PdfPages('Univariate_Boot_Estimates_plots.pdf') as pdf:
    for col in columns:
        sns.set_style("whitegrid")
        sns.set_palette(sns.color_palette("nipy_spectral"))
        sns.set_context("notebook", 
                        font_scale=1.3, 
                        rc={"lines.linewidth": 1.0})
        plt.figure(figsize=(12,3))
        plt.subplot(1,2,1)
        r2 = sns.pointplot(hue='method',
                    y=col,
                    x='percent', data=df_rest[df_rest['estimates'] == 'R2'], 
                      markers=['s','v','p','x'],  linestyles=["--",':',"-.",'-'])
        boot_HQ = col+'_HQ'
        boot_LQ = col+'_LQ'
        sns.scatterplot(hue='method',
                    y=boot_df[boot_HQ],
                    x='percent', data=boot_df[boot_df['estimates'] == 'R2'], 
                      markers=['s','v','p','x'],  linestyles=["--",':',"-.",'-'])
        sns.scatterplot(hue='method',
                    y=boot_df[boot_LQ],
                    x='percent', data=boot_df[boot_df['estimates'] == 'R2'], 
                      markers=['s','v','p','x'],  linestyles=["--",':',"-.",'-'])
#         _, ylabels = plt.yticks()
#         rmse.set_yticklabels(ylabels, size=10)
        _, xlabels = plt.xticks()
        r2.set_xticklabels(xlabels, size=10)
        plt.title(f"R2 plot of {col}", fontsize=12)
        plt.xlabel('Percent Missing', fontsize=10)
        plt.ylabel("R2 score", fontsize=10)
        # add labels here
        d1 = df[df['estimates'] == 'R2']
        d1 = d1.reset_index()
        plt.gca().get_legend().remove()
        
        ## Plot for R2
        plt.subplot(1,2,2)
        rmse = sns.pointplot(hue='method',
                    y=col,
                    x='percent', 
                    data=df_rest[df_rest['estimates']=='RMSE'],
                      markers=['s','v','p','x'],  linestyles=["--",':',"-.", '-'])
        rmse1 = sns.scatterplot(hue='method',
                    y=boot_df[boot_HQ],
                    x='percent', data=boot_df[boot_df['estimates'] == 'RMSE'],
                      markers=['s','v','p','x'],  linestyles=["--",':',"-.", '-'])
        rmse2 = sns.scatterplot(hue='method',
                    y=boot_df[boot_LQ],
                    x='percent', data=boot_df[boot_df['estimates'] == 'RMSE'],
                      markers=['s','v','p','x'],  linestyles=["--",':',"-.", '-'])
#         _, ylabels = plt.yticks()
#         r2.set_yticklabels(ylabels, size=10)
        _, xlabels = plt.xticks()
        rmse.set_xticklabels(xlabels, size=10)
        plt.title(f"RMSE plot of {col}", fontsize=12)
        plt.ylabel('RMSE error', fontsize=10)
        plt.xlabel('Percent Missing', fontsize=10)
        plt.gca().get_legend().remove()

#         handles, labels = plt.gca().get_legend_handles_labels()

#         l = plt.legend(handles, labels, bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)

        legend_without_duplicate_labels(plt)

        plt.tight_layout()    
        pdf.savefig()  # saves the current figure into a pdf page
        plt.close()

### Full Data

In [273]:
df1 = df[df['method'] == 'full']
boot_df1 = boot_df[boot_df['method'] == 'full']

In [275]:
df1

,estimates,method,percent,start_lat,start_lon,end_lat,end_lon,usertype,hour,temp,...,sealevelpressure,visibility,solarradiation,conditions,dist,birthyear,holiday,day,month,gender
0,R2,full,0%,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,...,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238,0.527238
1,RMSE,full,0%,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,...,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977,2.235977

In [276]:
columns = [ 'start_lat',
       'start_lon', 'end_lat', 'end_lon',
       'usertype', 'hour', 'temp', 'feelslike', 'dew', 'snowdepth', 'winddir',
       'sealevelpressure', 'solarradiation', 'conditions', 'dist', 'birthyear',
       'holiday', 'day', 'month', 'gender']
boot_columns = [['start_lat_HQ', 'start_lat_LQ'],
       ['start_lon_HQ', 'start_lon_LQ'], ['end_lat_HQ', 'end_lat_LQ'],
       ['end_lon_HQ', 'end_lon_LQ'], ['usertype_HQ', 'usertype_LQ'], ['hour_HQ',
       'hour_LQ'], ['temp_HQ', 'temp_LQ'], ['feelslike_HQ', 'feelslike_LQ'],
      [ 'dew_HQ', 'dew_LQ'],[ 'snowdepth_HQ', 'snowdepth_LQ'], ['winddir_HQ',
       'winddir_LQ'], ['sealevelpressure_HQ', 'sealevelpressure_LQ'],
       ['visibility_HQ', 'visibility_LQ'], ['solarradiation_HQ',
       'solarradiation_LQ'], ['conditions_HQ', 'conditions_LQ'], ['dist_HQ',
       'dist_LQ'],[ 'birthyear_HQ', 'birthyear_LQ'], ['holiday_HQ', 'holiday_LQ'],
       ['day_HQ', 'day_LQ'], ['month_HQ', 'month_LQ'], ['gender_HQ', 'gender_LQ']]
    
colors = [ "crimson", "yellow", "aqua","forestgreen","darkorange", ]

with PdfPages('complete_data_estimates.pdf') as pdf:
    for col in columns:
        sns.set_style("whitegrid")
        sns.set_palette(sns.color_palette(colors))
        sns.set_context("notebook", 
                        font_scale=1.3, 
                        rc={"lines.linewidth": 1.0})
        plt.figure(figsize=(12,3))
        plt.subplot(1,2,1)
        r2 = sns.pointplot(hue='method',
                    y=col,
                    x='percent', data=df1[df1['estimates'] == 'R2'])
        boot_HQ = col+'_HQ'
        boot_LQ = col+'_LQ'
        sns.scatterplot(hue='method',
                    y=boot_df1[boot_HQ],
                    x='percent', data=boot_df1[boot_df1['estimates'] == 'R2'])
        sns.scatterplot(hue='method',
                    y=boot_df1[boot_LQ],
                    x='percent', data=boot_df1[boot_df1['estimates'] == 'R2'])
#         _, ylabels = plt.yticks()
#         rmse.set_yticklabels(ylabels, size=10)
        _, xlabels = plt.xticks()
        r2.set_xticklabels(xlabels, size=10)
        plt.title(f"R2 plot of {col}", fontsize=12)
        plt.xlabel('Percent Missing', fontsize=10)
        plt.ylabel("R2 score", fontsize=10)
        # add labels here
        plt.gca().get_legend().remove()
        
        ## Plot for R2
        plt.subplot(1,2,2)
        rmse = sns.pointplot(hue='method',
                    y=col,
                    x='percent', 
                    data=df1[df1['estimates']=='RMSE'])
        rmse1 = sns.scatterplot(hue='method',
                    y=boot_df1[boot_HQ],
                    x='percent', data=boot_df1[boot_df1['estimates'] == 'RMSE'])
        rmse2 = sns.scatterplot(hue='method',
                    y=boot_df1[boot_LQ],
                    x='percent', data=boot_df1[boot_df1['estimates'] == 'RMSE'])
#         _, ylabels = plt.yticks()
#         r2.set_yticklabels(ylabels, size=10)
        _, xlabels = plt.xticks()
        rmse.set_xticklabels(xlabels, size=10)
        plt.title(f"RMSE plot of {col}", fontsize=12)
        plt.ylabel('RMSE error', fontsize=10)
        plt.xlabel('Percent Missing', fontsize=10)
        plt.gca().get_legend().remove()

        handles, labels = plt.gca().get_legend_handles_labels()

        l = plt.legend(handles, labels, bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
        plt.tight_layout()    
        pdf.savefig()  # saves the current figure into a pdf page
        plt.close()

## Except Full

In [277]:
df2 = df[df['method'] != 'full']
boot_df2 = boot_df[boot_df['method'] != 'full']

In [278]:
boot_df2

,estimates,method,percent,start_lat_HQ,start_lat_LQ,start_lon_HQ,start_lon_LQ,end_lat_HQ,end_lat_LQ,end_lon_HQ,...,birthyear_HQ,birthyear_LQ,holiday_HQ,holiday_LQ,day_HQ,day_LQ,month_HQ,month_LQ,gender_HQ,gender_LQ
0,R2,drop,1%,0.518931,0.534795,0.518931,0.534795,0.518931,0.534795,0.518931,...,0.518931,0.534795,0.518931,0.534795,0.518931,0.534795,0.518931,0.534795,0.518931,0.534795
1,RMSE,drop,1%,2.211797,2.257323,2.211797,2.257323,2.211797,2.257323,2.211797,...,2.211797,2.257323,2.211797,2.257323,2.211797,2.257323,2.211797,2.257323,2.211797,2.257323
2,intercept,drop,1%,-674.390226,-354.241091,-674.390226,-354.241091,-674.390226,-354.241091,-674.390226,...,-674.390226,-354.241091,-674.390226,-354.241091,-674.390226,-354.241091,-674.390226,-354.241091,-674.390226,-354.241091
3,R2,mode,1%,0.519730,0.535834,0.519750,0.535834,0.519748,0.535839,0.519726,...,0.519731,0.535842,0.519752,0.535840,0.519662,0.535780,0.519712,0.535816,0.519640,0.535782
4,RMSE,mode,1%,2.208209,2.255609,2.208182,2.255589,2.208197,2.255560,2.208220,...,2.208234,2.255623,2.208176,2.255563,2.208452,2.255691,2.208232,2.255618,2.208453,2.255683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,RMSE,bad,30%,2.208473,2.255920,2.210587,2.258307,2.208764,2.256194,2.210260,...,2.210124,2.257480,2.208325,2.255573,2.210743,2.258619,2.208451,2.256010,2.210842,2.258553
86,intercept,bad,30%,-583.083806,-300.837271,-932.139270,-650.278994,-538.192559,-253.924576,-421.922401,...,-660.941941,-377.332519,-645.984361,-363.976805,-649.487395,-363.624667,-648.149617,-366.106808,-660.010872,-376.217830
87,R2,bad,40%,0.519642,0.535759,0.518686,0.534920,0.519542,0.535618,0.518785,...,0.518640,0.534881,0.519667,0.535771,0.518494,0.534574,0.519595,0.535736,0.518483,0.534552
88,RMSE,bad,40%,2.208448,2.255920,2.210590,2.258331,2.208731,2.256186,2.210229,...,2.210626,2.258041,2.208378,2.255562,2.211439,2.259345,2.208530,2.256264,2.211705,2.259435
89,intercept,bad,40%,-586.736743,-306.261618,-936.960596,-652.812495,-544.565446,-255.863796,-424.401575,...,-663.048423,-381.246922,-645.804949,-364.557888,-651.043119,-363.256065,-648.851870,-367.973040,-657.402931,-375.410725

In [282]:
columns = [ 'start_lat',
       'start_lon', 'end_lat', 'end_lon',
       'usertype', 'hour', 'temp', 'feelslike', 'dew', 'snowdepth', 'winddir',
       'sealevelpressure', 'solarradiation', 'conditions', 'dist', 'birthyear',
       'holiday', 'day', 'month', 'gender']
boot_columns = [['start_lat_HQ', 'start_lat_LQ'],
       ['start_lon_HQ', 'start_lon_LQ'], ['end_lat_HQ', 'end_lat_LQ'],
       ['end_lon_HQ', 'end_lon_LQ'], ['usertype_HQ', 'usertype_LQ'], ['hour_HQ',
       'hour_LQ'], ['temp_HQ', 'temp_LQ'], ['feelslike_HQ', 'feelslike_LQ'],
      [ 'dew_HQ', 'dew_LQ'],[ 'snowdepth_HQ', 'snowdepth_LQ'], ['winddir_HQ',
       'winddir_LQ'], ['sealevelpressure_HQ', 'sealevelpressure_LQ'],
       ['visibility_HQ', 'visibility_LQ'], ['solarradiation_HQ',
       'solarradiation_LQ'], ['conditions_HQ', 'conditions_LQ'], ['dist_HQ',
       'dist_LQ'],[ 'birthyear_HQ', 'birthyear_LQ'], ['holiday_HQ', 'holiday_LQ'],
       ['day_HQ', 'day_LQ'], ['month_HQ', 'month_LQ'], ['gender_HQ', 'gender_LQ']]
    
colors = [ "teal", "yellow", "crimson","deepskyblue", "deeppink",]

with PdfPages('Univariate_Bootstrap_Estimates_Plots.pdf') as pdf:
    for col in columns:
        sns.set_style("whitegrid")
        sns.set_palette(sns.color_palette(colors))
        sns.set_context("notebook", 
                        font_scale=1.3, 
                        rc={"lines.linewidth": 1.0})
        plt.figure(figsize=(12,3))
        plt.subplot(1,2,1)
        r2 = sns.pointplot(hue='method',
                    y=col,
                    x='percent', data=df2[df2['estimates'] == 'R2'], 
                      markers=['o','s','v','p','x','o'],  linestyles=["-", "--",':',"-.",'-','--'])
        boot_HQ = col+'_HQ'
        boot_LQ = col+'_LQ'
        sns.scatterplot(hue='method',
                    y=boot_df2[boot_HQ],
                    x='percent', data=boot_df2[boot_df2['estimates'] == 'R2'], 
                      markers=['o','s','v','p','x','o'],  linestyles=["-", "--",':',"-.",'-','--'])
        sns.scatterplot(hue='method',
                    y=boot_df2[boot_LQ],
                    x='percent', data=boot_df2[boot_df2['estimates'] == 'R2'], 
                      markers=['o','s','v','p','x','o'],  linestyles=["-", "--",':',"-.",'-','--'])
#         _, ylabels = plt.yticks()
#         rmse.set_yticklabels(ylabels, size=10)
        _, xlabels = plt.xticks()
        r2.set_xticklabels(xlabels, size=10)
        plt.title(f"R2 plot of {col}", fontsize=12)
        plt.xlabel('Percent Missing', fontsize=10)
        plt.ylabel("R2 score", fontsize=10)
        # add labels here
        plt.gca().get_legend().remove()
        
        ## Plot for R2
        plt.subplot(1,2,2)
        rmse = sns.pointplot(hue='method',
                    y=col,
                    x='percent', 
                    data=df2[df2['estimates']=='RMSE'],
                      markers=['o','s','v','p','x','o'],  linestyles=["-", "--",':',"-.", '-','--'])
        rmse1 = sns.scatterplot(hue='method',
                    y=boot_df2[boot_HQ],
                    x='percent', data=boot_df2[boot_df2['estimates'] == 'RMSE'],
                      markers=['o','s','v','p','x','o'],  linestyles=["-", "--",':',"-.", '-','--'])
        rmse2 = sns.scatterplot(hue='method',
                    y=boot_df2[boot_LQ],
                    x='percent', data=boot_df2[boot_df2['estimates'] == 'RMSE'],
                      markers=['o','s','v','p','x','o'],  linestyles=["-", "--",':',"-.", '-','--'])
#         _, ylabels = plt.yticks()
#         r2.set_yticklabels(ylabels, size=10)
        _, xlabels = plt.xticks()
        rmse.set_xticklabels(xlabels, size=10)
        plt.title(f"RMSE plot of {col}", fontsize=12)
        plt.ylabel('RMSE error', fontsize=10)
        plt.xlabel('Percent Missing', fontsize=10)
        plt.gca().get_legend().remove()

#         handles, labels = plt.gca().get_legend_handles_labels()

#         l = plt.legend(handles, labels, bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
        legend_without_duplicate_labels(plt)
        plt.tight_layout()    
        pdf.savefig()  # saves the current figure into a pdf page
        plt.close()